### ISSUE TITLE
not support between  Double quotes content  

### ISSUE THREAD

**Issue by relunctance** [go-ini/ini#101]
can not support between  Double quotes content  

**like :** 
```
[db]
passwd="root123!@#QWE"   // '#' char  will be split
dsn="mysql:host=127.0.0.1;port=3306;dbname=test"  // ';' char  will be split 
```

**Comment by relunctance** [comment]
Comment

Take care that following format will be treated as comment:

Line begins with # or ;
Words after # or ;
Words after section name (i.e words after [some section name])
If you want to save a value with # or ;, please quote them with ` or """.

**Comment by Unknwon** [comment]
Alternatively, you can use following `LoadOptions` to completely ignore inline comments:

```go
cfg, err := LoadSources(LoadOptions{IgnoreInlineComment: true}, "app.ini"))
```
