### ISSUE TITLE
Struct map int with value 0. Incorrect value?

### ISSUE THREAD

**Issue by cez81** [go-ini/ini#103]
I have made this small example of an issue that I have at the moment. When mapping an ini to a struct, integer keys with value 0 will not return the correct value.
Could be a simple noob mistake... Thanks :)

test_ini.go (repo https://github.com/cez81/issue_103)
```
package main

import (
	"fmt"

	ini "gopkg.in/ini.v1"
)

type Person struct {
	Name string
	Age  int
}

func main() {
	p := struct {
		Name string
		Age  int
	}{
		Age: -1,
	}

	err := ini.MapTo(&p, "person.ini")
	if err != nil {
		fmt.Println(err)
	}

	fmt.Println(p)
}
```

person.ini
```
Name = Jonas
Age = 0
```

Run with Age = 0 set in ini and I get default value from struct init
```
jonas@lubuntu17:~$ go run ini.go 
{Jonas -1}
```
Run again with Age = 1 set in ini and I get correct value
```
jonas@lubuntu17:~$ go run ini.go 
{Jonas 1}
```

Edit: Using v1.27.2

**Comment by Unknwon** [comment]
This is because `0` is the zero-value for `int` type in Go, which means Go package can't tell the difference between a real `0` or the default value `0`.

**Comment by Unknwon** [comment]
But anyway, should be fixed by now.

**Comment by cez81** [comment]
Thanks, works as expected.
