### ISSUE TITLE
support default value for field

### ISSUE THREAD

**Issue by bruceauyeung** [go-ini/ini#105]
saying i have
~~~
[host]
ip=1.1.1.1
port=a30
~~~

my struct
~~~
type host struct {
    IP string `ini:"ip"`
    Port int `ini:"port"  default:22`
}
~~~
when i try to 
~~~
err = cfg.MapTo(h)
~~~
go-ini will fail to parse `a30` to an integer, then i expect go-ini set Port with default value `22`.
if using `StrictMapTo`, i expect go-ini also validate default value `22` before appling this value.

**Comment by Unknwon** [comment]
Hi, you can set default value by assign values when you create the actual object: https://github.com/go-ini/ini#map-to-struct.

I don't think it is necessary to another tag field because the current way also comes with nature validation from compiler.
