### ISSUE TITLE
Reading a key breaks when the value ends with a backslash character

### ISSUE THREAD

**Issue by nevcook** [go-ini/ini#114]
Given an ini file with the following contents:
```
[FileLocations]
ServerIniPath=D:\AppServer\Masters\
LabelPrint=C:\App\Print\LabelPrint.exe
EnvelopePrint=C:\App\Print\EnvelopePrint.exe
```
When reading the section "FileLocations" and the key "ServerIniPath" the trailing backslash on that line results in the following being returned `D:\AppServer\MastersLabelPrint=C:\App\Print\LabelPrint.exe`
This has joined the value from the key "ServerIniPath" with the following line.

My guess is that the trailing \ on that line has caused the following linefeed character to be escaped, rather than being treated as a normal line delimiter.

This is a running on a Windows system, so \ is just a path delimiter (like / in Linux).
The ServerIniPath entry represents a folder path, so while the trailing \ is obsolete, it is actually valid.
The file is written by another application, so I have no control over the format of the entries in the file, so I cannot enforce the entry to be written without the trailing \ or have the entry written enclosed in quotes, or make any other changes to the content of the file.

**Comment by Unknwon** [comment]
Hi, according to README:

![image](https://user-images.githubusercontent.com/2946214/29246393-78d4eb60-7fc6-11e7-96a3-b0397d210075.png)
