### ISSUE TITLE
.MapTo support url.URL

### ISSUE THREAD

**Issue by matheusd** [go-ini/ini#117]
Would you be interested in a PR to support url.URL structs when using the MapTo call? 

As I understand, it's a simple matter of changing the setWithProperType function, but I don't know whether you want to support types other than the built in.

**Comment by Unknwon** [comment]
Hi, this feature sounds similar to https://github.com/go-ini/ini/issues/84, the question how to know that what is the type that user wants to map as.

**Comment by matheusd** [comment]
When I thought about this issue, my idea was to include the URL type as a built-in type along with int, string, time, etc.

Mainly because URLs are so common, and go has a standard package to handle them. Didn't think about actual custom types.

**Comment by Unknwon** [comment]
Hmm... I think you should probably store the URL as string and parse it.

**Comment by matheusd** [comment]
That's what I'm doing today...

**Comment by Unknwon** [comment]
What is a robust way to detect a string is not a string but a `url.URL`?
