### ISSUE TITLE
Add default value feature to 'Map To Struct'  

### ISSUE THREAD

**Issue by xxwjj** [go-ini/ini#120]
Hi all, I new here. I just work for a golang project configuration feature, and foud this useful lib. "Map To Struct" is awesome feature , but there a little trouble if I want to define the struct default value. I think we can use golang struct Tag feature to implement this. The struct maybe define like this:

```
type Embeded struct {
	Places []string    `ini:"places,omitempty,default_value"`
}
```
Thanks and look forward to your reply.

**Comment by Unknwon** [comment]
Hi, if you initialize a struct with some values, when the value not present or not apply in the INI file, the value in struct variable will be not modified, which can be used as default value. Hope helps!
