### ISSUE TITLE
the characters after char # or ; in the value part should not be removed

### ISSUE THREAD

**Issue by ochinchina** [go-ini/ini#123]
some values contain # or ; character and they should be not regarded as inline comments and removed from the value.

For example:

value = this is a test;

in this example the value should be "this is a test;" instead of "this is a test"

**Comment by kuun** [comment]
I also have this problem, there is a field is password, it maybe contain character '#' or ';'

**Comment by Unknwon** [comment]
According to the README, you can use the following:

```go
key=`value#with special; char`
```

**Comment by KiddoV** [comment]
What if we cannot modify the INI file? Is there any work around to include these "special characters" in string?

**Comment by unknwon** [comment]
> What if we cannot modify the INI file? Is there any work around to include these "special characters" in string?

@KiddoV see example in https://github.com/gogs/gogs/blob/f4a78e5cfbd6f4a16b1f33784595d1b3ce3438e9/internal/conf/conf.go#L56
