### ISSUE TITLE
Default Section Behavior

### ISSUE THREAD

**Issue by jamesgoodhouse** [go-ini/ini#125]
### Please give general description of the problem
I am attempting to parse an AWS INI file. Most AWS ini files will have a section entitled `[default]`. When parsing the file with `go-ini` it keeps the `[default]` section, but takes all of the keys and puts them at the top of the file without a section. I dug through the source code a bit and found the variable `DefaultHeader`, which seems to be close to what I want. Unfortunately this duplicates everything in `[default]` and puts it under `[DEFAULT]`, which is not what I want. It also does not appear that I can change what the default section name is because it is set as the const `DEFAULT_SECTION`.

### Do you have any suggestion to fix the problem?
Possibly make `DEFAULT_SECTION` a variable instead of a const so that it can be set by the user? Another option is having the `InsensitiveLoad` function also ensure that `DEFAULT` is down-cased to `default`.

**Comment by placydo** [comment]
Wow. I just came here to report exactly same problem as You do for exactly same purpose You have.

**Comment by Unknwon** [comment]
Hi!

As suggested, now `InsensitiveLoad` enforces `DEFAULT_SECTION` to accept `[default]`. Please help test.

**Comment by placydo** [comment]
Thanks a lot. Will put it to test right now and let You how it works.

**Comment by jamesgoodhouse** [comment]
Awesome, we'll give it a try!
