### ISSUE TITLE
func (f *File) DeleteSection(name string) Does Not Delete Section

### ISSUE THREAD

**Issue by joeymiller** [go-ini/ini#127]
### Please give general description of the problem
Calling DeleteSection(name string) has no impact on file. Section never gets deleted.

### Please provide code snippets to reproduce the problem described above

func (c *Config) Remove() {
	if c.iniFile == nil {
		fmt.Println("No iniFile to add to")
	}

	c.iniFile.DeleteSection("sample")
}

**Comment by Unknwon** [comment]
File will not be touched until you write out to the file with same name.

**Comment by Unknwon** [comment]
@EverCurse sorry... I don't know what you're trying to ask?
