### ISSUE TITLE
Unescape comment symbols in value

### ISSUE THREAD

**Issue by lafriks** [go-ini/ini#129]
### Please give general description of the problem
As per ini file format `\;` should be treated as `;` when parsing

### Please provide code snippets to reproduce the problem described above
```
key = `test value <span style="color: %s; background: %s">more text</span>`
```
This value in crowdin is treated `test value <span style="color: %s` and after `;` it treats as comment

### Do you have any suggestion to fix the problem?
Add support for adding `\;` that would be parsed as `;` in value

**Comment by Unknwon** [comment]
Hi, are you sure you're using the latest version?

I cannot produce this problem in my test as follows:

File `test.ini`:
```ini
key = `test value <span style="color: %s; background: %s">more text</span>`
```

File `main.go`:
```go
package main

import (
	"fmt"
	"gopkg.in/ini.v1"
	"log"
)

func main() {
	f, err := ini.Load("test.ini")
	if err != nil {
		log.Fatal("Load:", err)
	}
	fmt.Println(f.Section("").Key("key").String())
}
```

Output:

```
test value <span style="color: %s; background: %s">more text</span>
```

**Comment by lafriks** [comment]
Problem is that when uploading to crowdin.com for translation such value will be split and part of it will be treated as comment. To correctly work it would be needed that value would be:
```
test value <span style="color: %s\; background: %s">more text</span>
```
But go-ini parser does not remove `\` as other ini parsers do

**Comment by Unknwon** [comment]
OK, I think I can add such unescape support, but will only unescape when the value part is not surrounded by kind of quotes, such as single quotes `'`, double quotes `"`, back quotes, etc. Because surrounded by quotes indicates preserve whatever in between in my opinion.

**Comment by lafriks** [comment]
As long as my provided example works I'm fine with that :)

**Comment by Unknwon** [comment]
You can now get latest version and test with:

```go
f, err := ini.LoadSources(ini.LoadOptions{
	IgnoreInlineComment:         true,
	UnescapeValueCommentSymbols: true,
}, "filename.ini")

...
```

**Comment by lafriks** [comment]
Is it possible to use this in go-macaron?

**Comment by Unknwon** [comment]
@lafriks ah... good point, go-macaron/i18n should have this option enabled by default.

**Comment by lafriks** [comment]
Thanks

**Comment by Unknwon** [comment]
OK, you will need to to update "github.com/Unknwon/i18n" and rebuild your program.

**Comment by lafriks** [comment]
Can it be escaped also when inside **`** 
For example:
```
COMMENT_SYMBOL = `test value <span style="color: \; background: ">more text</span>`
```

**Comment by Unknwon** [comment]
In this package, back quotes means do not change anything inside it, so I think it might not be appropriate to do that.

**Comment by lafriks** [comment]
Ok, than issue can be closed, thanks
