### ISSUE TITLE
Key value indention

### ISSUE THREAD

**Issue by udondan** [go-ini/ini#13]
Have not found anything so this probably is a feature request.

Is there a way to indent the key values pairs with some whitespaces? git for example uses an ini format like this:
```
[user]
        name = udondan
        email = udondan@github.com

[other section]
        foo = bar
```

`ini` can read this data but when writing it back it removes all the whitespaces. It would be great if there was an option to preserve whitespaces (detect when reading and write it back the same way) and/or define the desired number of spaces for the whole document.

**Comment by Unknwon** [comment]
Thanks your feedback!

Use `SaveToIndent` or `WriteToIndent` can use this feature.

**Comment by udondan** [comment]
Wow that was fast. Thanks! :+1:  I will try it tomorrow. :-)

**Comment by Unknwon** [comment]
No problem.
