### ISSUE TITLE
Support for AWS nested keys

### ISSUE THREAD

**Issue by lox** [go-ini/ini#131]
### Please give general description of the problem

So it seems that the aws-cli uses "[nested values](http://docs.aws.amazon.com/cli/latest/topic/config-vars.html#nested-values)", that look like this:

```
[profile testing]
aws_access_key_id = foo
aws_secret_access_key = bar
region = us-west-2
s3 =
  max_concurrent_requests=10
  max_queue_size=1000
```

I am trying to add a new key this profile and currently indenting is being reset on the "indented" keys. 

Is there anyway with go-ini to preserve that indented space?

**Comment by Unknwon** [comment]
Hi, for a quick look this style may not even work currently. So do you want to read and write such "nested values"? Seems pretty hard task... 😂

**Comment by lox** [comment]
Yup, currently this gets re-written as:

```
[profile testing]
aws_access_key_id = foo
aws_secret_access_key = bar
region = us-west-2
s3 =
max_concurrent_requests=10
max_queue_size=1000
```

It's terrible, but apparently that's what the aws-cli folks decided to do.

**Comment by Unknwon** [comment]
I'll try my best...

**Comment by Unknwon** [comment]
OK, to use this feature:

```go
	f, err := ini.LoadSources(ini.LoadOptions{
		AllowNestedValues: true,
	}, "aws.ini")

...

fmt.Println(f.Section("profile testing").Key("s3").NestedValues())
// Output: [max_concurrent_requests=10 max_queue_size=1000]
```

You can also add new nested values as follows:

```go
f.Section("profile testing").Key("s3").AddNestedValue("max_request_size=65535")
```

**Comment by lox** [comment]
Amazing @Unknwon, thanks so much!
