### ISSUE TITLE
When a line ends with \, the next line cannot be parsed correctly

### ISSUE THREAD

**Issue by huyi1985** [go-ini/ini#132]
### Please give general description of the problem
~~When a line ends with \, the next line cannot be parsed correctly~~
e.g.
```
test.ini
c = C:\
d = D:\
```
Sorry, I missed the advanced feature  'Read with multiple-line values.'. Using \ represents continuation lines is cool, but I think it has  a little conflict of Windows file path 

### Please provide code snippets to reproduce the problem described above
```
package main

import (
	"github.com/go-ini/ini"
	"fmt"
)

func main(){
	file := "test.ini"
	cfg, _ := ini.Load(file)

	c := cfg.Section("").Key("c").MustString("")
	d := cfg.Section("").Key("d").MustString("")

	fmt.Printf("c = %v, d = %v\n", c, d)
        // Output   c = C:d = D:, d = 
}
```

### Do you have any suggestion to fix the problem?
I'd like to fix this problem, but I'm newbie for Go

**Comment by heramerom** [comment]
It seems that you need to set `IgnoreContinuation = true` to resolve it.
```go
func TestINI(t *testing.T) {
	cfg, err := ini.LoadSources(ini.LoadOptions{IgnoreContinuation: true}, []byte(`
		A = C:\
		B = D:\
		`))
	if err != nil {
		panic(err)
	}
	t.Log(cfg.Section("").Key("A").String())
	t.Log(cfg.Section("").Key("B").String())
}

```

**Comment by Unknwon** [comment]
Thanks @heramerom!
