### ISSUE TITLE
LooseLoad meta data

### ISSUE THREAD

**Issue by greut** [go-ini/ini#134]
### Please give general description of the problem

I'm loading a config using the `LooseLoad` feature and would like to know which file was loaded.

### Please provide code snippets to reproduce the problem described above

```go
cfg, _ := ini.LooseLoad("a.ini", "b.ini", "c.ini")
_, err := cfg.GetSection("herp")¨

// How do I tell my user which file didn't have the `herp` section?
```

### Do you have any suggestion to fix the problem?

Enriching the `File` struct with the source used for the `parse` call.

https://github.com/go-ini/ini/blob/master/file.go#L198

**Comment by Unknwon** [comment]
Hi... I'm a bit confused with your need.

Do you want to know:

A. which files are loaded after `Load` or 
B. Which files do not have given section (e.g. `herp`)?

**Comment by greut** [comment]
The nature of `LooseLoad` is not what I want to have. I overlooked the fact that it loads from _all_ sources. Things are good, cheers,

**Comment by Unknwon** [comment]
:sweat_smile:...
