### ISSUE TITLE
Sections method panic

### ISSUE THREAD

**Issue by yarc123** [go-ini/ini#135]
### Please give general description of the problem
Sections method in concurrency got panic

### Do you have any suggestion to fix the problem?

Need to add lock mechanism

**Comment by Unknwon** [comment]
>Please provide code snippets to reproduce the problem described above

:slightly_smiling_face:

**Comment by yarc123** [comment]
code snippets:
`package main

import (
	"github.com/go-ini/ini"
	"strconv"
	"sync"
)

const section_prefix = "TEST"

func number_of_section(cfg *ini.File) {
	for {
		_ = len(cfg.Sections())
	}
}
func number_of_section1(cfg *ini.File) {
	for {
		_ = len(cfg.Sections())
	}
}

func add_section(cfg *ini.File, i int, wg *sync.WaitGroup) {
	section_name := section_prefix + strconv.Itoa(i)
	cfg.NewSection(section_name)
	wg.Done()
}

func main() {

	cfg := ini.Empty()
	var wg sync.WaitGroup
	go number_of_section(cfg)
	go number_of_section1(cfg)
	for i := 0; i < 10000; i++ {
		wg.Add(1)
		go add_section(cfg, i, &wg)
	}
	wg.Wait()
}`

`panic: runtime error: index out of range

goroutine 5 [running]:
github.com/go-ini/ini.(*File).Sections(0xc420090000, 0xc4207f0000, 0x21f, 0x21f)
	/home/wasim/golang/src/github.com/go-ini/ini/file.go:146 +0x13f
main.number_of_section(0xc420090000)
	/home/wasim/schema/tmp_plugin/cfg_panic.go:31 +0x2b
created by main.main
	/home/wasim/schema/tmp_plugin/cfg_panic.go:51 +0x2d0
exit status 2`

**Comment by yarc123** [comment]
Can you please reopen this ticket?

Thanks

**Comment by Unknwon** [comment]
Hi, can you test again against `master` branch?

**Comment by yarc123** [comment]
thanks, it's O.K now
