### ISSUE TITLE
support multi value with same key 

### ISSUE THREAD

**Issue by cnlizg** [go-ini/ini#136]
[IP]
value = 192.168.31.201
value = 192.168.31.211
value = 192.168.31.221

**Comment by Unknwon** [comment]
Hmm, it is already supported. Couldn't find the docs, maybe I forgot to add...

You can learn how to do it by example before I update the README: https://github.com/go-ini/ini/blob/master/ini_test.go#L215-L224

**Comment by Unknwon** [comment]
Added.

**Comment by cnlizg** [comment]
great! thanks!

**Comment by cnlizg** [comment]
Mapto don't support Shadow

**Comment by Unknwon** [comment]
Provide your code and configuration examples.

**Comment by cnlizg** [comment]
package main

import (
   "gopkg.in/ini.v1"
   "log"
)

type IP struct {
   Value    []string `ini:"value"`
}

func main() {
   iniconf := `[IP]
value = 192.168.31.201
value = 192.168.31.211
value = 192.168.31.221`
   cfg, err := ini.ShadowLoad([]byte(iniconf))
   if err != nil {
      log.Fatal(err)
   }
   
   note := new(IP)
   for _, section := range cfg.Sections() {
      if err = section.MapTo(note);err != nil {
         log.Println(err)
      } else {
         log.Println(section.Name(), note.Value)
      }
   }
}

**Comment by cnlizg** [comment]
IP [192.168.31.201]

**Comment by Unknwon** [comment]
See https://github.com/go-ini/ini/issues/92#issuecomment-286312120.

I'll add to docs.
