### ISSUE TITLE
Support multiline comments.

### ISSUE THREAD

**Issue by Backfighter** [go-ini/ini#138]
### Please give general description of the problem
If the comment for a key is set to something containing line breaks, new line will not have a ';' before them which breaks the configuration file.

### Please provide code snippets to reproduce the problem described above
```golang
package main

import (
	"bytes"
	"fmt"

	"github.com/go-ini/ini"
)

func main() {
	cfg := ini.Empty()
	section := cfg.Section("")
	k := section.Key("test")
	k.Comment = "Multiline\nComment"
	output := bytes.NewBufferString("")
	_, _ = cfg.WriteTo(output)
	fmt.Printf("Ouput: \n%s", output.String())
	// Expected:
	// Ouput:
	// ; Multiline
	// ; Comment
	// test =
	// Actual:
	// Ouput:
	// ; Multiline
	// Comment
	// test =
}
```

### Do you have any suggestion to fix the problem?
Newline characters could be converted into '\n ;' when writing.

**Comment by Unknwon** [comment]
Such support has been added via https://github.com/go-ini/ini/commit/5e9692864e22d02ac79e2fa499cffb00520b4fea, please re-pull the package and help test!
