### ISSUE TITLE
Support SetValue() to receive interface{} type value

### ISSUE THREAD

**Issue by hzmnet** [go-ini/ini#139]
sometimes we want to set a bool to the key. but it is unsupported now

**Comment by Unknwon** [comment]
Hi, for your needs, I suggest to add a new method (i.e. `SetBool`) other than change behavior of existing method because people may have different ways of how to convert a type of value to a string.

**Comment by hzmnet** [comment]
and then what about covert to int int64.....

**Comment by Unknwon** [comment]
Yes, we need a method for every supported type. As getters like `Int()`, `Int64()`, so there is no automagic happens.
