### ISSUE TITLE
Redis密码含有`#` 时，无法连接Redis服务

### ISSUE THREAD

**Issue by MiderWong** [go-ini/ini#141]
#### **解决方案1 [可用]：**
修改密码，去掉密码中的特殊字符

但是我想试试其它的解决方案，于是就有了下面的实验性尝试。。。。

#### **解决方案2 ：**
使用`go-ini`官方文档给出的方案，在有特殊字符的地方使用 ``` ` ```或者``` """ ```，全都尝试过了，实验I和II，是明显错误，因为Gogs使用的是`Macaron` 框架的中间件，没有继续研究，所以实验III和IV的具体原因和解决办法暂时还不清楚，不过可以确定的是，`Redis`密码无误
##### 实验代码I：
```
HOST = network=tcp,addr=:6379,password=`redis#$%12322`,db=15,pool_size=100,idle_timeout=180
```
错误提示：
```
panic: missing closing key quote from '`redis' to ''
```
打印出来解析后的配置内容如下：
```
network=tcp,addr=:6379,password=`redis
```
##### 实验代码II：
```
HOST = network=tcp,addr=:6379,password="""redis#$%12322""",db=15,pool_size=100,idle_timeout=180
```
错误提示如下：
```
panic: missing closing key quote from '"""redis' to ''
```
打印出来解析后的配置内容如下：
```
network=tcp,addr=:6379,password="""redis
```
##### 实验代码III：
```
HOST = `network=tcp,addr=:6379,password=redis#$%12322,db=15,pool_size=100,idle_timeout=180`
```
错误提示如下：
```
panic: ERR invalid password
```
打印出来解析后的配置内容如下：
```
network=tcp,addr=:6379,password=redis#$%12322,db=15,pool_size=100,idle_timeout=180
```
##### 实验代码IV：
```
HOST = """network=tcp,addr=:6379,password=redis#$%12322,db=15,pool_size=100,idle_timeout=180"""
```
错误提示如下：
```
panic: ERR invalid password
```
打印出来解析后的配置内容如下：
```
network=tcp,addr=:6379,password=redis#$%12322,db=15,pool_size=100,idle_timeout=180
```
#### **解决方案3：**
`go-ini`文档注明，可以通过使用以下代码来完全忽略行内注释：

```
cfg, err := ini.LoadSources(ini.LoadOptions{
    IgnoreInlineComment: true,
}, "app.ini")
```
于是我修改了`Gogs`的`setting.go`文件：
将`405`行中的内容：
```
Cfg, err = ini.Load(bindata.MustAsset("conf/app.ini"))
```
改为：
```
Cfg, err = ini.Load(ini.LoadOptions{IgnoreInlineComment:true,}, bindata.MustAsset("conf/app.ini"))
```
但是在编译的时候，提示如下错误：
```
# github.com/gogits/gogs/pkg/setting
pkg/setting/setting.go:406:57: unknown field 'IgnoreInlineComment' in struct literal of type ini.LoadOptions
```
求告知，如何解决这个难题？不管从解决方案2中III、IV入手或者从解决方案3入手都可以，只要可以解决问题。

**Comment by MiderWong** [comment]
沉了？？？？？？？？
真不该手欠想着从`GitLab`转到`Gogs`......

既然一条龙套件服务的大哥都不帮忙，我把这个比较低级的解决方案放到这里就让他沉了吧。
找到 #93 中的解决方案，具体在`Gogs`中的解决方案就是：
注释掉`vendor/gopkg.in/ini.v1/parser.go`中第`228`行的代码：
```
// i := strings.IndexAny(line, "#;")
        // if i > -1 {
        //      p.comment.WriteString(line[i:])
        //      line = strings.TrimSpace(line[:i])
        // }
```

**Comment by getso-guo** [comment]
1、注释掉并不能从根本解决问题吧？
2、作者估计看不懂中文。

**Comment by getso-guo** [comment]
`i := strings.IndexAny(line, "#;")
        if i > -1 {
             p.comment.WriteString(line[i:])
             line = strings.TrimSpace(line[:i])
        }`
改成
`i := strings.IndexAny(line, "#;")
        if i  == 0 {
             p.comment.WriteString(line[i:])
             line = strings.TrimSpace(line[:i])
        }`

**Comment by getso-guo** [comment]
if i > -1 盖首if i == -1会不会好点。这样注释就只有在开头

**Comment by gnodli** [comment]
哈哈，碰到了同样的问题
