### ISSUE TITLE
Load file from HTTP/HTTPS

### ISSUE THREAD

**Issue by ccfish86** [go-ini/ini#142]
### Please give general description of the problem
因从spring cloud过来的，一些轮子，觉得还是比较有趣的。
像配置中心（远程配置文件），可以把管理不同的环境下的配置文件及修改版本，修改后能push到对应的环境中，并达到热替换的效果
### Please provide code snippets to reproduce the problem described above
这个spring cloud config-server，[携程开源的apollo（基于前者）](https://github.com/ctripcorp/apollo)
### Do you have any suggestion to fix the problem?
能有最好了，没有的话，遇到类似的需求，一般大家都怎么处理？

**Comment by Unknwon** [comment]
Hi, if you're talking about load configuration from a remote URL (e.g. `http://mydomain.com/config.ini`), then it is workable. Otherwise, I think it's out of scope of this package's focus.
