### ISSUE TITLE
On full COW filesystems os.Create will truncate but never create new file

### ISSUE THREAD

**Issue by szaydel** [go-ini/ini#15]
I found that on a full volume, on a COW filesystem like ZFS, because any write means copy first, if you are saving a change to already existing INI file, truncation with os.Create will happen, but changed contents are not written out, because of the nature of COW.

This is one way of solving this problem. I am not sure it is worth your time, but I do see this as a problem in general. Before a file is saved, we should make sure previous version is not lost until save is known to be good.

**My attempt**: `https://github.com/szaydel/ini/commit/7d5632418e212b9d519f8d31803532dc3a3ee97e`

**Comment by Unknwon** [comment]
Thanks your feedback!

I have exactly same thought as your commit does after read your comments.

But I would suggest save with unique filename(in the middle) because it could happen that multiple threads call Save method.

Besides, shouldn't put those changes in `SaveToIndent`?

PS: Do you want to make a PR on it, or let me do this?

**Comment by szaydel** [comment]
It sounds like you already know what you want, so I'd say go for it, else I certainly can make changes to the `SaveToIndent` as per your suggested improvements. Let me know!

**Comment by Unknwon** [comment]
Hi @szaydel , I've pushed some code, please help review and test!

**Comment by czxichen** [comment]
ini.go 1107 行.
//defer fw.Close()
if _, err = f.WriteToIndent(fw, indent); err != nil {
	fw.Close()
	return err
}
//Remove old file and rename the new one.
os.Remove(filename)
fw.Close()
return os.Rename(tmpPath, filename) //用defer这里会报错.

**Comment by Unknwon** [comment]
@czxichen thanks! You're absolutely right, and I've pushed fix again, please help check. :grinning:

**Comment by szaydel** [comment]
I apologize, have been really busy for last couple of days. I shall test today and offer feedback if I think something looks like it could be a problem. Thanks!

**Comment by szaydel** [comment]
Maybe I am just knit-picking, but I would instead of rolling my own method use the ioutil's tempfile.

You get back a struct of *os.File and it is guaranteed to be unique by implementation.
newf, _ := ioutil.TempFile(".", "tmp.")

What do you think?

**Comment by Unknwon** [comment]
Hi @szaydel yeah, it's fine! And yes use standard lib as much as possible is the ideal. But by reading the [source code](https://github.com/golang/go/blob/master/src/io/ioutil/tempfile.go#L47) of this function, it is kind of too complicated for just generate a unique file name(timestamp solves almost everything).

And in terms of lines of code, I think both of them are one line... :smiley:
