### ISSUE TITLE
Add option to skip unrecognizable lines

### ISSUE THREAD

**Issue by Maxiride** [go-ini/ini#150]
### Please give general description of the problem
I'm working with configuration files that come with colons as key value delimiter and I can't do anything about it.

### Do you have any suggestion to fix the problem?
Is there a way to set the colon as a delimiter other than digging into the package code itself to change it?

Edit:
Roughly tried to change [this](https://github.com/go-ini/ini/blob/7af1ffd45d624cf8a055ae35ab74ea007d9377c6/parser.go#L130) line but I still get `Fail to read file: key-value delimiter not found`

**Comment by Unknwon** [comment]
Hi, this library supports `:` by nature. Please show example input.

**Comment by Maxiride** [comment]
I'm sorry, upon further investigation I indeed have "illegal" lines hence deviating from the pure ini schema.

[Here]( https://gist.github.com/Maxiride/aef9703c26f09baa3b03d89594340a80#file-worldconfig-ini-L49-L50) is a sample file, namely lines 49 and 50 are "illegal ini lines".

Is there a workaround to enable the parser to simply skip and ignore such occurences?

**Comment by Maxiride** [comment]
That would be ideal! As I don't need to modify those lines I really don't need them to be parsed at all.

Would it be too much of an hassle to implement such option for you?

**Comment by Unknwon** [comment]
Should be an easy fix but my flight is about to departure. I'll work on it once I back home.

**Comment by Maxiride** [comment]
Thank you very much for your availability 😉

**Comment by Unknwon** [comment]
Here you go: https://ini.unknwon.io/docs/howto/load_data_sources#skip-unrecognizable-lines

**Comment by Maxiride** [comment]
Thank you very very much for new option!

I really appreciate that :)



_Sent from my OnePlus3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Maxiride** [comment]
Can confirm that works perfectly as expected, again I'm honoured for the custom option you made just for this case =)

Best wishes.
