### ISSUE TITLE
file.go: LoadOptions and dataSource are undefined

### ISSUE THREAD

**Issue by rhalff** [go-ini/ini#153]
### Please give general description of the problem

I'm trying to build the docker image from peachdocs and get errors for this `go-ini` package.

### Please provide code snippets to reproduce the problem described above

As quick reproduce just try to build the peachdocs docker image.

```
# gopkg.in/ini.v1
../../../gopkg.in/ini.v1/file.go:30: undefined: LoadOptions
../../../gopkg.in/ini.v1/file.go:31: undefined: dataSource
```

### Do you have any suggestion to fix the problem?

I'm not familar enough with these go packages.

**Comment by Unknwon** [comment]
Hi, looks like you're using Go version lower than Go 1.6, consider upgrade.
