### ISSUE TITLE
SaveTo function change comments such as adding semicolon as starting for comments line

### ISSUE THREAD

**Issue by rossmeng** [go-ini/ini#157]
### general description of the problem
**I have a simple conf file "myconf" looks like as following:**
[myconf.txt](https://github.com/go-ini/ini/files/2299287/myconf.txt)

**basically, I want to read the file and change the field "domain" and only it then save the content back, don't touch any other value even comments. but the result is not my expectation result, which adding a semicolon in comment line and remove some space for comment line**
**I use following go code to reproduce the problem:**
```go
package main

import (
  "fmt"
  "os"
  "gopkg.in/ini.v1"
)
func testini() {

    cfg, err := ini.Load("myconf")
    if err != nil {
        fmt.Printf("Fail to read file: %v", err)
        os.Exit(1)
    }
 
    cfg.Section("general").Key("domain").SetValue("mydomain.com")
    cfg.SaveTo("myconf.local")

}

func main() {
	testini()
}
```

**I get the result "myconf.local" as following:**
[myconflocal.txt](https://github.com/go-ini/ini/files/2299290/myconflocal.txt)

**I am not sure if I don't use the API correctly or not, why should we need to change the comments since they are good to start with #, we might just let them alone.**

**If I use the API correctly to read/write, my suggestion to fix the problem will looks like following:**
[ini_patch_no_semicolone.txt](https://github.com/go-ini/ini/files/2299289/ini_patch_no_semicolone.txt)

Does it make sense to you, thank you very much

**Comment by Unknwon** [comment]
Thanks for the feedback!

I can confirm this is a bug and fix has been pushed to `master` branch, please re-fetch `github.com/go-ini/ini` to test the fix.

**Comment by rossmeng** [comment]
Thanks your quickly respond for that.
I update the code and test, the result are same when write out.
the ";" still be added for each line starting.
Could you please check my pacth file "ini_patch_no_semicolone.txt" to check the related code how to fix that? I am very appreciate for your help.

**Comment by Unknwon** [comment]
I think you didn’t update the package as I advised. What is the command you used to update this package?

**Comment by rossmeng** [comment]
The problem was fixed with the latest master code. Thanks
