### ISSUE TITLE
function "In", "InInt" and probably rest of "In" functions does not save keys to file

### ISSUE THREAD

**Issue by audrius-paskevicius** [go-ini/ini#158]
If i do:

	iniFilePath = filepath.Join(HomeDir, iniFileName)
	cfg, err := ini.Load(iniFilePath)

	ParityVal := cfg.Section(PortSelVal).Key("Parity").In("N", []string{"N", "O", "E", "M", "S"})
	StopBitsVal := cfg.Section(PortSelVal).Key("StopBits").InInt(1, []int{1, 2, 15})
	cfg.SaveTo(iniFilePath)

on the initially empty file i get only:

Parity      = 
StopBits    = 

but if i do:

	iniFilePath = filepath.Join(HomeDir, iniFileName)
	cfg, err := ini.Load(iniFilePath)

	ParityVal := cfg.Section(PortSelVal).Key("Parity").In("N", []string{"N", "O", "E", "M", "S"})
	StopBitsVal := cfg.Section(PortSelVal).Key("StopBits").InInt(1, []int{1, 2, 15})
	cfg.Section(PortSelVal).Key("Parity").SetValue(ParityVal)
	cfg.SaveTo(iniFilePath)

then, on initially empty file i get:

Parity      = N
StopBits    = 

"SetValue" accepts strings, so:

cfg.Section(PortSelVal).Key("StopBits").SetValue(StopBitsVal)

would be wrong.

I assume "SetValue" step should be unnecessary. How can i deal with that? Do i miss something?

**Comment by Unknwon** [comment]
Hi, what you have found is expected, `In...` methods are only for helping you to assure values on read. The only way to modify the original file (content) is by calling `SetValue`.
