### ISSUE TITLE
Support ini files with multiple key/values in one line starting after a space

### ISSUE THREAD

**Issue by erharb** [go-ini/ini#159]
It would be great to be able to support the INI file style used by Ansible, which is interesting in that it can have keys with no values or multiple key/value pairs in one line. It doesn't need to map keys between sections just strings would be perfect.

https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html

Example inventory.ini file:
```
localhost              ansible_connection=local
other1     ansible_connection=ssh        ansible_user=mpdehaan
other2     ansible_connection=ssh        ansible_user=mdehaan

[webservers]
other1
other2
```

I guess in this case "other1" in the default section up top could be a key that leads to a map that then has key "ansible_connection" with value "ssh"

**Comment by Unknwon** [comment]
Keys without values is already supportted:

https://ini.unknwon.io/docs/howto/work_with_keys#mysql-like-boolean-key

But multiple keys in one line is somewhat I think asking too much for a INI file.

**Comment by erharb** [comment]
Thanks for showing the boolean key, that helps me with one part. As for the other request, perhaps instead of actually parsing out multiple key value pairs in one line, what about just giving the value of the remainder of the line so we can parse ourselves as needed? For example:

`other1     ansible_connection=ssh        ansible_user=mpdehaan`

becomes key="other1", value="ansible_connection=ssh        ansible_user=mpdehaan"

**Comment by Unknwon** [comment]
You have to have a "=" or ":" to indicate who is key and who is value, " " (in your particular case) is a bad choice in my opinion.
