### ISSUE TITLE
GetKey auto-creates all child sections

### ISSUE THREAD

**Issue by johnl** [go-ini/ini#16]
When calling GetKey in a section with dots in the section name, child sections are created.

So I have a ini file with a section with dots in the name:
```
[john@example.co.uk]
id = bleh
```

I read the file in, modify the id key and write the file back out and end up with this:

```
[john@example.co.uk]
id = bleh

[john@example.co]

[john@example]
```

I think the problem is here, where GetKey calls Section for all child nodes: https://github.com/go-ini/ini/blob/v1/ini.go#L516

It should instead check if each section exists, rather than auto-creating it.

**Comment by Unknwon** [comment]
Thanks your feedback!

**Comment by Unknwon** [comment]
Hi! I've pushed a quick fix, please help test again!

**Comment by johnl** [comment]
tested and looks good to me! Thanks!

**Comment by Unknwon** [comment]
Thanks your confirmation!
