### ISSUE TITLE
I don't understand the meaning of this judgment.

### ISSUE THREAD

**Issue by KiripengTsai** [go-ini/ini#160]
### Please give general description of the problem
in the  ini/parser.go have the code
### Please provide code snippets to reproduce the problem described above
```go
switch {
	case mask[0] == 254 && mask[1] == 255:
		fallthrough
	..........
	}
	return nil
```
if we don't use the code judgement ,why we should write the judgement? 
### Do you have any suggestion to fix the problem?

**Comment by Unknwon** [comment]
Maybe helpful: https://github.com/golang/go/wiki/Switch#fall-through
