### ISSUE TITLE
Add option to have padding spaces around equal sign when PrettyFormat is disabled

### ISSUE THREAD

**Issue by haroldHT** [go-ini/ini#161]
There should be a way to close "PrettyFormat" when you init config
I do not want to " a         = 123"
I just want to "a = 123"

**Comment by haroldHT** [comment]
you can use `ini.PrettyFormat=false`
But it will be 
`a=1
ab=3`
What I want is 
`a = 1
ab = 3`

Can I choose the indent after key?

**Comment by haroldHT** [comment]
By the way

**Comment by haroldHT** [comment]
I want to support multiple the same sections like：
`[global]
a=1
[global]
ab=1
`

The reason  why I do that is I do not want to change some configuration format.

**Comment by Unknwon** [comment]
Hi, multiple section with same name is not and will not be supported at least in current version of this package. I've adjusted the title for your initial feature request.

**Comment by haroldHT** [comment]
我可以加入开发吗，请问

**Comment by Unknwon** [comment]
Yes you can send a pull request :grin:

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging #164.
