### ISSUE TITLE
The key contains ":" to create ini file will add "`" before and after the key ?

### ISSUE THREAD

**Issue by toranger** [go-ini/ini#163]
### Please give general description of the problem
when the key has ":" , such like this  "s3:125244888:lewzyluyfb111" the lib function to create ini file will contains "`" lead to the result is " `s3:125244888:lewzyluyfb111` " , it there any solution to this problem to create normal ini file?

**Comment by Unknwon** [comment]
Try 
```
`s3:125244888:lewzyluyfb111` = value
```

**Comment by toranger** [comment]
> Try
> 
> ```
> `s3:125244888:lewzyluyfb111` = value
> ```

what does it mean? save it with " ` " then result will not have "`" ?

**Comment by Unknwon** [comment]
Sorry I couldn't understand your goal... but back quotes is used to preserve anything within it as a whole when you have special characters that conflict with this package.

**Comment by toranger** [comment]
> Sorry I couldn't understand your goal... but back quotes is used to preserve anything within it as a whole when you have special characters that conflict with this package.

when the key has the  ":" , then use the lib to create ini file, this key in that file will has the "`" , such like
"`keypart1:keypart2`", I want to know how to clear this "`"?

**Comment by toranger** [comment]
> Sorry I couldn't understand your goal... but back quotes is used to preserve anything within it as a whole when you have special characters that conflict with this package.

It there any config or other way to solve this conflict?

**Comment by Unknwon** [comment]
>It there any config or other way to solve this conflict?

You can't because `:` is a delimiter of key and value, without surrounding quotes next time will be read as wrong result.

**Comment by toranger** [comment]
> > It there any config or other way to solve this conflict?
> 
> You can't because `:` is a delimiter of key and value, without surrounding quotes next time will be read as wrong result.

Are there other delimiters here? or somewhere docs I can read to get?

**Comment by Unknwon** [comment]
In fact, someone has implemented custom delimiter after your request:

https://github.com/go-ini/ini/blob/9c8236e659b76e87bf02044d06fde8683008ff3e/ini.go#L171-L172

**Comment by toranger** [comment]
Get it. but how can I change it only use "=" as delimiters

**Comment by Unknwon** [comment]
See tests as example:

https://github.com/go-ini/ini/blob/9c8236e659b76e87bf02044d06fde8683008ff3e/ini_test.go#L1235-L1250

**Comment by toranger** [comment]
Good!  I use it mem->file->mem->file. Does it need to be use both create ini file and analysis?

**Comment by Unknwon** [comment]
>Does it need to be use both create ini file and analysis?

Sorry, I don't understand what it means?

**Comment by toranger** [comment]
> > Does it need to be use both create ini file and analysis?
> 
> Sorry, I don't understand what it means?

If a file contain the ":" delimiter, such like "  key:v1=value " , Should I use the same way which limit the delimiter is ":" to load this file?

**Comment by toranger** [comment]
> First of all, upgrade to the latest version.
> 
> Second, give out steps.

cfg, err := ini.LoadSources(ini.LoadOptions{                                                                                                                                             
        KeyValueDelimiters: "=",                                                                                                                                                             
    }, filePath)

I used this way to load file, begin to create ini file.
but if comments has spaces in the head, after creating file there are some comments have two spaces in the head.
the code just like that:
for _, ci := range ns.Items {                                                                                                                                                    
                _, err = sec.NewKey(ci.Key, ci.Value)                                                                                                                                        
                if err != nil {                                                                                                                                                              
                    glog.Error("ini new keyPrefix failed", err.Error())                                                                                                                      
                    return err                                                                                                                                                               
                }                                                                                                                                                                            
                sec.Key(ci.Key).Comment = ci.Comment                                                                                                                                         
}

**Comment by toranger** [comment]
If I create a ini file with the delimiter "=", Do I need to analysis this file with the same ini.loadSources with the same delimiter "=", so that it can keey the same format?

**Comment by toranger** [comment]
func main() {                                                                                                                                                                                
                                                                                                                                                                                             
    filePath := "./testor"                                                                                                                                                                   
    os.Create(filePath)                                                                                                                                                                      
    cfg, err := ini.LoadSources(ini.LoadOptions{                                                                                                                                             
        KeyValueDelimiters: "=",                                                                                                                                                             
    }, filePath)                                                                                                                                                                             
    if err != nil {                                                                                                                                                                          
        return                                                                                                                                                                               
    }                                                                                                                                                                                        
    sec := cfg.Section("test1")                                                                                                                                                              
    _, err = sec.NewKey("opp", "w")                                                                                                                                                          
    sec.Key("tmd").Comment = " comment"                                                                                                                                                      
    cfg.SaveTo(filePath)                                                                                                                                                                     
}

Found out, when use this way to create file, If the comment has space behand, the file created has two spaces

**Comment by Unknwon** [comment]
Thanks, I've pushed a patch to fix this issue. Please re-fetch the package and test.

**Comment by toranger** [comment]
ok，when the comment with the mult ";" it seems only delete first one and add "; " with space

**Comment by Unknwon** [comment]
>when the comment with the mult ";"

Well, that's your syntax issue.
