### ISSUE TITLE
Support customize delimiters

### ISSUE THREAD

**Issue by forest0** [go-ini/ini#166]
It seems that the parser takes `=:` as delimiters, can you provide an option
to let users customize their delimiters?

Currently I am parsing a file whose keys contain `:`, say `keee:y=value`,
since `:` is viewed as a delimiter, I can not extract `keee:y` as the key.

**Comment by Unknwon** [comment]
If you can edit the file, try :

```ini
"keee:y"= value
```

**Comment by forest0** [comment]
Thanks for your reply.

The application I am writing configuration for can just understand the format like `keee:y=value`,
i.e., `"` is illegal.

At present, to get it work, I have to modify some lines of this library to let `:` is not viewed as a delimiter.

**Comment by Unknwon** [comment]
> Thanks for your reply.
> 
> The application I am writing configuration for can just understand the format like `keee:y=value`,
> i.e., `"` is illegal.
> 
> At present, to get it work, I have to modify some lines of this library to let `:` is not viewed as a delimiter.

Thanks, make sense to me, I'll come up something.

**Comment by Unknwon** [comment]
Pull the latest change, and try as follows:

https://github.com/go-ini/ini/blob/9c8236e659b76e87bf02044d06fde8683008ff3e/ini_test.go#L1235-L1243

**Comment by forest0** [comment]
Nice work! 👍
