### ISSUE TITLE
support for custom field defaults

### ISSUE THREAD

**Issue by fpawel** [go-ini/ini#167]
Hi, and good for you!

### Please give general description of the problem

I would like to be able to set the values of deserialized structure fields by default

### Please provide code snippets to reproduce the problem described above

Suppose I want to deserialize the COM port settings like this

```
type ComportConfig struct {
	Name  string
	Baud   int
	ReadTimeout time.Duration 
}
var x ComportConfig
ini.Empty().MapTo(&x) // x fields has default falues, it's not good, because we need to validate and set all the values manualy
```

### Do you have any suggestion to fix the problem?

```
type ComportConfig struct {
	Name  string `default:"COM1"`
	Baud   int `default:"9600"`
	ReadTimeout time.Duration `default:"1000000"` 
}
var x ComportConfig
ini.Empty().MapTo(&x) 
// x.Name == "COM1"
// x.Baud == 9600
// x.ReadTimeout == time.Millisecond
```

**Comment by Unknwon** [comment]
I think currently you're able to set the value of the struct before call of `MapTo`, if the data read is not presented or invalid, the value of fields remain unchanged.
