### ISSUE TITLE
semicolon can't be parsed

### ISSUE THREAD

**Issue by newthinker** [go-ini/ini#169]
If the value contains a semicolon, the parsing will be truncated.
eg: value = abc;def, the parsed value is "abc"

My code:
	cfg, err := ini.InsensitiveLoad(cfgPath)
	if err != nil {
		return err
	}

        var conf BaseConfig
	c := new(BaseConfig)
	err = cfg.MapTo(c)

**Comment by Unknwon** [comment]
Yes, because it is a symbol for comment.

Ref: https://ini.unknwon.io/docs/howto/work_with_comments
