### ISSUE TITLE
Cannot update config file on Windows after v1 branch merge

### ISSUE THREAD

**Issue by tooda02** [go-ini/ini#17]
go-ini is broken on Windows after the [v1 branch merge](https://github.com/go-ini/ini/commit/a1b79207164a3d5a358cad0550fa4), as it is no longer able to update its configuration file.  Calls to SaveTo() fail with a message similar to:

> ERROR Unable to update config file C:\Users\David\.shipped\shipped.ini with apiToken=RLUtmYgmSVYBADDvoxIfsfgPyCKmxIub: rename C:\Users\David\.shipped\
shipped.ini.555854800.tmp C:\Users\David\.shipped\shipped.ini: Cannot create a file when that file already exists.

The problem is in the new code that writes the update into a temporary file and then attempts to remove the old file and rename the new.  In Windows, you cannot remove an open file, so the os.Remove(filename) towards the end of SaveToIndent() fails.  This call does not check for errors; if it did, it would show an error similar to:

> Unable to remove C:\Users\David\.shipped\shipped.ini: remove C:\Users\David\.shipped\shipped.ini: The process cannot access the file because it is being used by another process.

**Comment by Unknwon** [comment]
Thanks your feedback!

Are you suggesting that add an error check is good enough for you?

FYI, the new code was introduced by https://github.com/go-ini/ini/issues/15 .

**Comment by tooda02** [comment]
Adding an error check is not enough, as the library will still be unusable on Windows.  Are you able to close the file (so that the remove works)?  If not, can you revert to the previous approach for updating config on Windows?

**Comment by Unknwon** [comment]
> Are you able to close the file (so that the remove works)

I don't understand this, go-ini closes file right after parsing.

**Comment by Unknwon** [comment]
I've pushed a fix to `v1` branch which closes file after parsing.

**Comment by tooda02** [comment]
That did it!  go-ini again works on Windows.  Thanks for the quick response.

**Comment by Unknwon** [comment]
:wink:
