### ISSUE TITLE
Unreachable code in parser.go

### ISSUE THREAD

**Issue by octomarat** [go-ini/ini#170]
Hi!

I am writing a tool to detect unreachable code in Go programs. I used your project to test it and found an issue here:
https://github.com/go-ini/ini/blob/9c8236e659b76e87bf02044d06fde8683008ff3e/parser.go#L311

This `if` statement is never executed. This is because the only way to exit the loop above is through `return` statements. 
I tried to remove this statement. Compiler showed that `identSize` variable became unused. So I removed it also. After that, I ran all the tests and none failed. Not sure if this could be an evidence of some bug in the behavior of the parser.

**Comment by Unknwon** [comment]
Thanks, after a quick digging, I think it is most likely redundant.

**Comment by Unknwon** [comment]
Fixed, thanks again!
