### ISSUE TITLE
Short-circuit load

### ISSUE THREAD

**Issue by optimusgrue** [go-ini/ini#180]
This is a feature request, not a bug.

It would possibly be useful to be able to do something like this:

`
cfg, err := ini.LazyLoad("./foo.ini", "/usr/local/etc/foo.ini", "/etc/foo.ini")
`

Instead of overwriting keys or creating shadow keys, LazyLoad would stop after the first successful loading of an ini file.

This could be done two ways:

1. Passing a new LoadOptions field named something like AllowShortCircuit to LoadSources.

2. Repeated calling LoadSources from LazyLoad.

LazyLoad is perhaps not the best name, but I am not very creative with names.

I might work on this myself, but it will be a couple of weeks before I have the time.

Edit to add: Obviously this can be done already with nested if statements, or a helper function.

**Comment by optimusgrue** [comment]
A naive implementation of method 2 from above might look like this:

`
func LazyLoad(sources ...interface{}) (*File, error) {

    var fp *File
    var err error
    for i := range sources {
        fp, err = LoadSources(ini.LoadOptions{}, sources[i])
    	if err == nil {
			return fp, err
		}
	}
    return fp, err
}
`

**Comment by Unknwon** [comment]
Thanks for the feedback!

>Passing a new LoadOptions field named something like AllowShortCircuit to LoadSources.

This idea looks better in my point of view.

**Comment by glefloch** [comment]
@Unknwon would you accept a PR for this feature request?

**Comment by Unknwon** [comment]
@glefloch Yes, a PR would be great to have!

**Comment by ygj6** [comment]
This is really useful for my current project, and I made a simple change to [Reload()](https://github.com/ygj6/ini/commit/93cee51a369dde34896c3c639aad5e33585368cc) to implement this feature.
```go
func (f *File) Reload() (err error) {
	for i, s := range f.dataSources {
		if err = f.reload(s); err != nil {
			// Notice: if AllowShortCircuit and Loose are both true, AllowShortCircuit has priority over Loose.
			// Return err when all configuration sources fail to load.
			if f.options.AllowShortCircuit {
				if i < len(f.dataSources)-1 {
					continue
				}
				return err
			}
			// In loose mode, we create an empty default section for nonexistent files.
			if os.IsNotExist(err) && f.options.Loose {
				_ = f.parse(bytes.NewBuffer(nil))
				continue
			}
			return err
		}
		if f.options.AllowShortCircuit {
			return nil
		}
	}
	return nil
}
```
But there's a special scenario, if `AllowShortCircuit` and `Loose` are both true, `AllowShortCircuit` has priority over `Loose`.

**Comment by unknwon** [comment]
Implemented in https://github.com/go-ini/ini/pull/261.
