### ISSUE TITLE
Does this support modify the field separator by arguments or options? e.g. a:b instead of a=b

### ISSUE THREAD

**Issue by smthemofbl** [go-ini/ini#184]
### Please give general description of the problem
Does this support modify the field separator by arguments or options? e.g. a:b
### Please provide code snippets to reproduce the problem described above
NA
### Do you have any suggestion to fix the problem?
dunno

**Comment by Unknwon** [comment]
Hi,

>Does this support modify the field separator by arguments or options? e.g. a:b

What is "arguments" or "options"?
