### ISSUE TITLE
关于 ShadowLoad 和 ValueWithShadows 读取重复键值的疑问.

### ISSUE THREAD

**Issue by senioi** [go-ini/ini#185]
ini 文件

```ini
> [list]
> type = 1
> min_time = 11
> min_code = 20
> time = 1,11,30,21,30
> time = 2,11,30,22,30
> time = 3,11,30,21,30
> time = 4,11,30,21,30
> time = 5,11,30,22,30
> time = 6,11,30,10,30,13,30,16,30,22,30
> time = 7,11,30,10,30,13,30,16,30,21,30
> 
> [list]
> type = 2
> min_time = 22
> min_code = 20
> time = 1,12,30,21,30
> time = 2,12,30,22,30
> time = 3,12,30,21,30
> time = 4,12,30,21,30
> time = 5,12,30,22,30
> time = 6,12,30,10,30,13,30,16,30,22,30
```

set, err := ini.ShadowLoad("./time.ini")
set.Section(`list`).Key("time").ValueWithShadows()

这样会把第二个list的也读取了,
于是我尝试

type list struct {
	type       []int    `ini:"type ,omitempty,allowshadow"`
	min_time    []int    `ini:"min_time ,omitempty,allowshadow"`
	time []string `ini:"time ,omitempty,allowshadow"`
}

这样的话,只会读取到最后一个 time = xxx

请问大神,如何优雅的读取这个配置文件?

**Comment by Unknwon** [comment]
老哥，你这样的配置。。适合自己写个脚本解析。。反正也不是很复杂的格式。这个库目前不支持重名的 section
