### ISSUE TITLE
Does the NewKey() function unsorted key when save to local file?

### ISSUE THREAD

**Issue by toranger** [go-ini/ini#188]
### Please give general description of the problem
Unsorted key to call the NewKey() function then call the SaveTo() to local file, the keys in this local file do not sorted. Do I need to sort the keys before call the NewKey()?

### Please provide code snippets to reproduce the problem described above
cfg, err := ini.LoadSources(ini.LoadOptions{
        KeyValueDelimiters: "=",
    }, filePath)
    if err != nil {
        glog.Error("ini fail to read file", err.Error())
        return err
    }
    for _, ns := range i.Cf.Namespaces {
        sec := cfg.Section(ns.Namespace)
        // Check whether has parent_namespace
        if len(ns.ParentNamespace) == 0 {
            for _, ci := range ns.Items {
                _, err = sec.NewKey(ci.Key, ci.Value)
                if err != nil {
                    glog.Error("ini new keyPrefix failed", err.Error())
                    return err
                }
                sec.Key(ci.Key).Comment = ci.Comment
            }
            err := cfg.SaveTo(filePath)
            if err != nil {
                glog.Error("when save tmp config.ini failed")
                return err
            }
        } else {
            // TODO According the Specific Format to solve the third nesting
        }
    }

### Do you have any suggestion to fix the problem?
Sort before save to local file ?

**Comment by Unknwon** [comment]
Hi, new key appends to the key list which is the last position. There is no such feature that sorts key in this package.

**Comment by toranger** [comment]
Get it. I use this to create config file, when diff the history version found sections and keys are not sorted, so hard to diff.

**Comment by Unknwon** [comment]
Ideally, we could add a method to sort the sections/keys, is that what you want?

**Comment by toranger** [comment]
> Ideally, we could add a method to sort the sections/keys, is that what you want?

Sort the sections and keys may be can not suit other user situation(I guess), if it can control whether to sort, might be very nice!

**Comment by Unknwon** [comment]
>Sort the sections and keys may be can not suit other user situation(I guess), if it can control whether to sort, might be very nice!

Sure, it would be something like `f.SortSections`, `sec.SortKeys`, which you must call them explicitly.
