### ISSUE TITLE
non unique sections

### ISSUE THREAD

**Issue by aligator** [go-ini/ini#190]
### Please give general description of the problem
Wireguard has ini files like this:
[Interface]
Address = 192.168.2.1
PrivateKey = <server's privatekey>
ListenPort = 51820

[Peer]
PublicKey = <client's publickey>
AllowedIPs = 192.168.2.2/32

[Peer]
PublicKey = <client2's publickey>
AllowedIPs = 192.168.2.3/32

And there can be unlimited [Peer] sections.
Is it currently possible to parse / write such an ini-file?

### Do you have any suggestion to fix the problem?
I haven't found anything about this so I already tried it myself: https://github.com/aligator/ini/tree/nonUniqueSections
This already works for ini.LoadSources and f.WriteTo but I haven't tested it very much.
Edit: now for ini.MapTo also (but not f.Section("Peer").MapTo)

And I don't know where else in the source I have to add support for this...
If you have any hints for me it would be great :-)

**Comment by Unknwon** [comment]
Hi, glad you got it working! You could send a PR from your fork to this repository, I will review but I can't promise it would be merged in advance.

**Comment by aligator** [comment]
It's not finished yet, and currently I have some other projects I work on. Don't know when I work on this again. (It's on my todo-list :-) Should I create a WIP PR so that it doesn't get lost if someone else needs this functionality or wants to finish the work?

**Comment by Unknwon** [comment]
@aligator no pressures!

**Comment by unknwon** [comment]
Hey, what is the status of this?

**Comment by aligator** [comment]
Oh, sorry, I am still working on other projects and as always I have not enough time... I haven't worked on this yet.

**Comment by unknwon** [comment]
Thanks for the info! No worries, just checking.

**Comment by Place1** [comment]
I've run into the same limitation, trying to parse the same wireguard config as well haha. I'd be keen to see support for this.

**Comment by vx3r** [comment]
anything new about this issue ?
