### ISSUE TITLE
Add interfaces to allow mocking and testing

### ISSUE THREAD

**Issue by ishankhare07** [go-ini/ini#193]
### Please give general description of the problem
Currently the code does not uses interface definitions. This makes the code using `ini` very hard to test as there is not an easy way to mock `ini`

### Please provide code snippets to reproduce the problem described above
currently if i try to use [golang/mock](https://github.com/golang/mock) in order to mock, say `ini.File`, it will result in an error as its defined as a struct and not an interface.

This is the same case when trying with [impl](https://github.com/josharian/impl)

### Do you have any suggestion to fix the problem?
Add interface definitions for struct types that `ini` uses. This will allow easy mocking as any user code will then accept and return these `interfaces` which can easily be mocked during tests. With little guidance, I would be happy to contribute on this issue.

**Comment by Unknwon** [comment]
Thanks for the feedback! But it would introduce major API breaks since everything operation would become a method call when use interface definitions.

BTW, in what way, you're trying mock and test this library?
