### ISSUE TITLE
using Insensitive option breaks DEFAULT section

### ISSUE THREAD

**Issue by sgtsquiggs** [go-ini/ini#198]
### Please give general description of the problem
Loading a file with a [DEFAULT] section and using the Insensitive option causes an empty [default] section, while keeping the existing [DEFAULT] section. [DEFAULT] values are inaccessible.

### Do you have any suggestion to fix the problem?
Offending line is here: https://github.com/go-ini/ini/blob/master/file.go#L71
When called from here: https://github.com/go-ini/ini/blob/master/parser.go#L405
When name = "DEFAULT"

**Comment by unknwon** [comment]
Hi, can you provide code snippets to reproduce the problem described above?

**Comment by unknwon** [comment]
I made a test case but is not able to reproduce:

https://github.com/go-ini/ini/blob/e145131f9c53ce7ec360723789d1c16641fad02a/ini_test.go#L270-L281

Is something wrong with my understanding of the problem?
