### ISSUE TITLE
Set quota if value have whitespace or empty

### ISSUE THREAD

**Issue by Lasiar** [go-ini/ini#202]
### Please give general description of the problem
How can wrap value in quota if value have whitespace or empty?

### Please provide code snippets to reproduce the problem described above
input:
```
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
GRUB_CMDLINE_LINUX=""
```

output: 
```
GRUB_CMDLINE_LINUX_DEFAULT=quiet splash
GRUB_CMDLINE_LINUX=
```

### Do you have any suggestion to fix the problem?
Rude decision:
```go
for _, cfgSection := range cfg.Sections() {
	for _, cfgKey := range cfgSection.Keys() {
		cfgKey.SetValue(wrappingQuota(cfgKey.Value()))
	}
}
```

**Comment by unknwon** [comment]
Thanks for the feedback! 

I'm curious what's the use case?
