### ISSUE TITLE
Bugs occur when backslashes are used at the end of a line

### ISSUE THREAD

**Issue by z-yuanhao** [go-ini/ini#204]
like this:
[app]
SqlDir = C:\Users\Jeremy\Desktop\AutoDump\\
ImeiFile = C:\Users\Jeremy\Desktop\imei.txt

you can not get ImeiFile‘s value

**Comment by unknwon** [comment]
Hi, you can quote the value, or disable continuation lines feature:

```go
cfg, err := ini.LoadSources(ini.LoadOptions{
    IgnoreContinuation: true,
}, "filename")
```
