### ISSUE TITLE
Desired behavior when creating a new ini file

### ISSUE THREAD

**Issue by jmcfarlane** [go-ini/ini#21]
When using `ini.load()` to read a file that doesn't exist, you can proceed to use the returned object to make changes and ultimately persist the object to disk via `SaveTo`, however it looses the top level section. I fixed the issue in my program by making sure the ini file was initialized as an empty file (if missing) prior to loading, but I wondered what the intended behavior is in this case.

Here's an example program to illustrate the question:

```
package main

import (
	"fmt"
	"gopkg.in/ini.v1"
)

func main() {
	p := "/tmp/missing-file.ini"
	cfg, err := ini.Load(p)
	fmt.Println(cfg, err)
	cfg.Section("section").NewKey("key", "value")
	cfg.SaveTo(p)
}
```

Running the program results in this:

```
$ go run test.go
&{true {{0 0} 0 0 0 0} [{/tmp/missing-file.ini}] map[] [] <nil>} open /tmp/missing-file.ini: no such file or directory
$ cat /tmp/missing-file.ini
key = value
```

Because the write ultimately succeeded, running the same program again
has this result:

```
$ go run test.go
&{true {{0 0} 0 0 0 0} [{/tmp/missing-file.ini}] map[DEFAULT:0xc820018190] [DEFAULT] <nil>} <nil>
$ cat /tmp/missing-file.ini
key = value

[section]
key = value
```

Any thoughts on if this is the intended behavior? My instinct is that this is a defect, and the library should either write the correct textual representation of the object, or it should fail to write because the file doesn't exist (consistent with `err` returned by `ini.load()`).

**Comment by Unknwon** [comment]
Hi, you're right!

I've pushed code to return `nil` for `cfg` when error is presented, please `go get -u` update can test again.

**Comment by jmcfarlane** [comment]
After updating my local copy of go-ini via `go get -u` I see the code has changed, but the behavior (as seen by the test snippet I pasted originally) has not changed. `ini.Load()` is still returning an object, where I think the intent of the change was to return `nil` in the "file is missing" case.

**Comment by Unknwon** [comment]
Based on https://github.com/go-ini/ini/blob/v1/ini_test.go#L122-L124 , I think your test processing is not correct. And I get panic by running your test.

**Comment by jmcfarlane** [comment]
Indeed! I had my import specified via `"gopkg.in/ini.v1"` so I wasn't actually seeing your commit. Testing against `"github.com/go-ini/ini"` and I now see a panic. Thanks :)

**Comment by Unknwon** [comment]
:beers:
