### ISSUE TITLE
\r\n auto remove when load from ini file?

### ISSUE THREAD

**Issue by toranger** [go-ini/ini#216]
### Please give general description of the problem
Can write window \r\n into the value then create config file, but when load this config file can not found the \r\n does the lib changed it? or can this lib support the situation?

### Do you have any suggestion to fix the problem?
want to know how to avoid this problem, want the input and output always same.

**Comment by unknwon** [comment]
Hi, thanks for the feedback!

However, I think something is missing from the [issue template](https://github.com/go-ini/ini/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by toranger** [comment]
[example.txt](https://github.com/go-ini/ini/files/3866858/example.txt)
here is example code. sample to save and load

**Comment by unknwon** [comment]
Thanks, could you point out what do you expect to see but what you see instead more specifically?

**Comment by toranger** [comment]
expect to see save the original value into the file, but when load from the config file origin \n is not exist,  in other words can this support windows \r\n in key and value?

**Comment by unknwon** [comment]
I'm sorry but it's really hard for me to understand. Are you talking about the line breaks? `\n` for non-Windows and `\r\n` for windows?
