### ISSUE TITLE
DefaultSection is lowercase in some cases

### ISSUE THREAD

**Issue by mtibben** [go-ini/ini#217]
When using `ini.LoadSources` with `Insensitive: true`, `default` is returned when calling `SectionStrings`. This means you cannot use `DefaultSection` to identify the default section.  Instead I would expect `DEFAULT` to be returned.

Testcase: https://github.com/go-ini/ini/commit/7066eed (first test succeeds, second test fails)

**Comment by unknwon** [comment]
Hmm, you could just use empty string `""`, you don't have to use `DefaultSection`. 

Ref: https://ini.unknwon.io/docs/howto/work_with_sections
