### ISSUE TITLE
Cannot reflect unexported struct

### ISSUE THREAD

**Issue by ehudkaldor** [go-ini/ini#223]
**Describe the bug**
Cannot reflect unexported struct

**To Reproduce**
Create an unexported struct (`type myStruct struct`) and save with ReflectFrom

**Expected behavior**
Be able to save unexported structs from the same package it's defined in

**Screenshots**

**Additional context**
I'm a noob to golang, but it seems the `reflect` library can work with unexported structs. I am reflecting a config struct used by the same package that defines it (with getters/setters external access), but getting a reflection error:
```
2020/02/16 06:04:39 created empty ini
2020/02/16 06:04:39 reflecting struct
panic: reflect.Value.Interface: cannot return value obtained from unexported field or method

goroutine 1 [running]:
reflect.valueInterface(0x561502d075a0, 0xc0000866e8, 0x1b8, 0x1, 0x561502cf0000, 0xf)
	/usr/lib/go/src/reflect/value.go:1014 +0x1be
reflect.Value.Interface(...)
	/usr/lib/go/src/reflect/value.go:1003
gopkg.in/ini%2ev1.(*Section).reflectFrom(0xc000086770, 0x561502d69d40, 0xc000086690, 0x199, 0xc000086690, 0x199)
	/root/go/src/gopkg.in/ini.v1/struct.go:539 +0x258
gopkg.in/ini%2ev1.(*Section).ReflectFrom(0xc000086770, 0x561502d5a8a0, 0xc000086690, 0xc000086770, 0x0)
	/root/go/src/gopkg.in/ini.v1/struct.go:598 +0x14a
gopkg.in/ini%2ev1.(*File).ReflectFrom(0xc0000e20c0, 0x561502d5a8a0, 0xc000086690, 0xc0000ddb40, 0xc000096000)
	/root/go/src/gopkg.in/ini.v1/struct.go:603 +0x57
gopkg.in/ini%2ev1.ReflectFromWithMapper(...)
	/root/go/src/gopkg.in/ini.v1/struct.go:609
gopkg.in/ini%2ev1.ReflectFrom(...)
	/root/go/src/gopkg.in/ini.v1/struct.go:614
```

**Comment by unknwon** [comment]
Hi, this is limited by Go's runtime, not in control of this package.

**Comment by ehudkaldor** [comment]
as i said, i'm a noob. but i found this:
https://stackoverflow.com/questions/42664837/access-unexported-fields-in-golang-reflect

would `DeepEqual` be useful to allow this?

**Comment by unknwon** [comment]
I looked at that thread too, but I do not think use `unsafe` package in a general purpose utility library is a wise choice.

**Comment by ehudkaldor** [comment]
fair enough. thank you

**Comment by itswisdomagain** [comment]
How about ignoring unexported fields instead of panicking? I find that the problem is really not with unexported struct types but with unexported fields in a struct.

**Comment by unknwon** [comment]
@itswisdomagain tried with a quick hack and seems worked: https://github.com/go-ini/ini/pull/239

**Comment by itswisdomagain** [comment]
Yeah, that should do it. Thanks!
