### ISSUE TITLE
ini reads a file with `:` as delimiter, but saves with `=` as delimiter

### ISSUE THREAD

**Issue by ehudkaldor** [go-ini/ini#224]
**Describe the bug**
`ini` reads a file with `:` as delimiter, but saves with `=` as delimiter

**To Reproduce**
as described above

**Expected behavior**
Either `ini` should remember the delimiter used during load, or it should have an option to provide a delimiter, like `LoadOptions` does for LoadResource()

**Additional context**
snippet of read:

	iniContent, loadErr := ini.Load(configPath)
	if loadErr != nil {
		log.Println("Failed loading config file", configPath, loadErr)
		return loadErr
	}

	tempConfig := new(Config)
	mapErr := iniContent.Section("Agent").MapTo(tempConfig)
	if mapErr != nil {
		log.Println("Failed to map config file", mapErr)
		return mapErr
	}
	MyConfig = tempConfig

snippet of write:

	cfg := ini.Empty()
	cfg.NewSection("Agent")
	reflectError := cfg.Section("Agent").ReflectFrom(MyConfig)
	if reflectError != nil {
		log.Println("Failed reflecting config info", reflectError)
		return reflectError
	}
	writeError := cfg.SaveTo(configPath)
	if writeError != nil {
		log.Println(fmt.Sprintf("Failed saving bouncer config info into %v", configPath), writeError)
		return writeError
	}

snippet of struct:

	type Config struct {
		FUSEVolumeName               string  `ini:"FUSEVolumeName"`
	...
	}

snippet of file before read:

	[Agent]
	FUSEVolumeName:                                    CommonVolume
	...

snippet of file after save:

	[Agent]
	FUSEVolumeName               = CommonVolume
	...

**Comment by unknwon** [comment]
Thanks for bringing this up! There was a PR about this, feel free to pick it up :) https://github.com/go-ini/ini/pull/203

**Comment by ehudkaldor** [comment]
while i appreciate the trust, i was hoping i'm doing something wrong. but i am working on a quick project, and getting familiar with the code and writing tests will probably take exponential time more than, after saving the file, run a golang replacer to replace all `=` to `:`.

i will try to get back to this PR at some point.

**Comment by aligator** [comment]
this PR should fix this issue: https://github.com/go-ini/ini/pull/226

So I think this can be closed.

**Comment by unknwon** [comment]
Yep, the solution here is to use this load option:

https://github.com/go-ini/ini/blob/8e0f5b3a15fc93a84881c6cc50129bd62e83a314/ini.go#L106-L107
