### ISSUE TITLE
Type reflection panic on embedded pointer field

### ISSUE THREAD

**Issue by unbyte** [go-ini/ini#225]
**Describe the bug**
When use `reflectFrom()` on a nest struct , it leads to a panic like  `panic: interface conversion: interface {} is , not Time.time`

**To Reproduce**
```go
type Cfg struct {
	Rpc           *Rpc           `ini:"rpc"`
}

type Rpc struct {
	Enable  bool   `ini:"enable"`
	Type    string `ini:"type"`
	Address string `ini:"addr"`
	Name    string `ini:"name"`
}

func (i *Rpc) IsServer() bool {
	return i.Type == "server"
}

func (i *Rpc) IsClient() bool {
	return i.Type == "client"
}

func EmptyConfig() *Cfg {
	return &Cfg{
		Rpc:           &Rpc{},
        }
}

...
cfg := EmptyConfig()
tmp := ini.Empty()
tmp.ReflectFrom(cfg)
...
```

**Expected behavior**
Work well

**Screenshots**

**Additional context**
I commented two lines [here](https://github.com/go-ini/ini/blob/master/struct.go#L477) and it work successfully

**Comment by unknwon** [comment]
Thanks for the feedback!

Just testing, what if you removed the pointer:

```go
type Cfg struct {
	Rpc           Rpc           `ini:"rpc"`
}
```

Will it still panic?

**Comment by unbyte** [comment]
nope, of course

the point is the wrong type judgment for variables of `Ptr` kind after value taking.

i found a related issue [here](https://github.com/go-ini/ini/issues/61). maybe there is a better way to judge whether a variable is of `time.Time`
