### ISSUE TITLE
ini 这个包文档的地址国内是不是访问不了

### ISSUE THREAD

**Issue by c-jf** [go-ini/ini#236]
我在不翻墙的情况下无法访问 ini 这个包文档的地址，是否放在国外的服务器上，如果是请问作者有国内的地址吗，我这边无法翻墙

**Comment by unknwon** [comment]
老哥你运气真好。。我刚备案了一个域名，可以放一个国内地址。。

**Comment by unknwon** [comment]
https://ini.unknwon.cn
