### ISSUE TITLE
parse the windows driver setup information(INF)

### ISSUE THREAD

**Issue by RangoW** [go-ini/ini#237]
**Describe the bug**
can't parse the section[AddReg]

**To Reproduce**
INF contains  like this :

```
[Version]
signature   = "$CHICAGO$"
Class       = Media
ClassGUID   = {4d36e96c-e325-11ce-bfc1-08002be10318}
Provider    = %Vendor%
CatalogFile = emWHQL.cat
DriverVer   = 11/18/2019, 5.2019.1118.0

[Capture2860.Interface]
AddReg = Capture.2860.AddReg

[Capture.2860.AddReg]
HKR,,CLSID,,%ProxyVCap.CLSID%
HKR,,FriendlyName,,%Cap.2860.Name%
; IAMVideoCompression installed as static interface on both output pins
HKR,PinFactory\0\Interfaces\{C6E13343-30AC-11d0-A18C-00A0C9118956},,,{C6E13343-30AC-11d0-A18C-00A0C9118956}
HKR,PinFactory\1\Interfaces\{C6E13343-30AC-11d0-A18C-00A0C9118956},,,{C6E13343-30AC-11d0-A18C-00A0C9118956}
```

**Expected behavior**
```
PS C:\Users\rango\go\src\gopkg.in\ini> go test -v -run TestFile_GetSection

=== RUN   TestFile_GetSection

  Get a section x


Failures:

  * C:/Users/rango/go/src/gopkg.in/ini/file_test.go
  Line 234:
  Expected: nil
  Actual:   'key-value delimiter not found: HKR,,CLSID,,%ProxyVCap.CLSID%
```

**Comment by unknwon** [comment]
Hi, by looking at the error, I don't see anything wrong with the parser, because there is in fact no key-value delimiter in the line `HKR,,CLSID,,%ProxyVCap.CLSID%`.

If you want to parse the section as a whole raw string, see [Unparseable Sections](https://ini.unknwon.io/docs/howto/work_with_sections#unparseable-sections).

**Comment by RangoW** [comment]
I can't know which section is unparseable in advance。。
`cfg, err := ini.LoadSources(ini.LoadOptions{
    UnparseableSections: []string{"COMMENTS"},
}, `[COMMENTS]
<1><L.Slide#2> This slide has the fuel listed in the wrong units <e.1>`)`  , maybe the "COMMNETS“  is  a regular expression?

**Comment by unknwon** [comment]
> I can't know which section is unparseable in advance

OK... that is a problem, do you care about these lines? If no, you can [Skip Unrecognizable Lines](https://ini.unknwon.io/docs/howto/load_data_sources#skip-unrecognizable-lines).

**Comment by RangoW** [comment]
Em. I will skip these lines. Very thanks.
