### ISSUE TITLE
feature: expand ~ on Load

### ISSUE THREAD

**Issue by greenpau** [go-ini/ini#245]
The `Load("~/.aws/credentials")` results in file not found. The issue is the expanding of tilde `~`. It would be nice to auto expand `~` and environment variables, e.g. `HOME`.

**Comment by greenpau** [comment]
Something along the lines of:

```
import (
    "io/ioutil"
    "os"
    "path/filepath"
)

func expandHomePath(fp string) (string, error) {
    if fp[0] != '~' {
        return fp, nil
    }
    hd, err := os.UserHomeDir()
    if err != nil {
        return fp, err
    }
    fp = filepath.Join(hd, fp[1:])
    return fp, nil
}

func readFileBytes(fp string) ([]byte, error) {
    var err error
    fp, err = expandHomePath(fp)
    if err != nil {
        return nil, err
    }
    return ioutil.ReadFile(fp)
}
```

**Comment by unknwon** [comment]
Thanks for the feedback!

It is not deterministic that `~` should always be expanded to home directory. Suggest using the result of `os.ExpandEnv` as the file name, see example: https://play.golang.org/p/HZtHz0x7Ayu
