### ISSUE TITLE
struct is null on use mapto

### ISSUE THREAD

**Issue by Chen-kaiyuan** [go-ini/ini#249]
**struct is null on use mapto**
I'm tying  cfg map to struct called redis1. but when fmt.printf redis1 is always shows up with empty values
If I use: cfg.Section("Redis").GetKey("Password")
I can get access to the Value for "Password"

Am I trying to use MapTo incorrectly?

**To Reproduce**
`
package main

import (
	"fmt"
	"github.com/go-ini/ini"
	"time"
)

type redis1 struct {
	HOST       string
	PASSWORD   string
	MAXIDIE    int
	MAXACTIVE  int
	TIMEOUT    time.Duration
}

func main()  {

	cfg, err := ini.Load("conf/app.ini")
	if err!= nil{
		fmt.Println(err)
	}
	redis121 := new(redis1)
	_ = cfg.Section("Redis").MapTo(redis121)
	fmt.Println(redis121)

	c1 ,_:= cfg.Section("Redis").GetKey("Password")
	fmt.Println(c1)
}
`

**Screenshots**
![image](https://user-images.githubusercontent.com/17740259/88357371-99ac8000-cd9d-11ea-81cd-8a3893f602f7.png)

**Comment by ygj6** [comment]
You can add tags in the structure to map the `Password`  in the ini file.
```
type redis1 struct {
HOST string
PASSWORD string `ini:"Password"`
MAXIDIE int
MAXACTIVE int
TIMEOUT time.Duration
}
```

output
```
&{ mypassword 0 0 0s}
mypassword

Process finished with exit code 0
```

**Comment by Chen-kaiyuan** [comment]
> You can add tags in the structure to map the `Password` in the ini file.
> 
> ```
> type redis1 struct {
> HOST string
> PASSWORD string `ini:"Password"`
> MAXIDIE int
> MAXACTIVE int
> TIMEOUT time.Duration
> }
> ```
> 
> output
> 
> ```
> &{ mypassword 0 0 0s}
> mypassword
> 
> Process finished with exit code 0
> ```

ths !
![image](https://user-images.githubusercontent.com/17740259/88469807-b4126500-cf27-11ea-81c8-02bcc6e4b488.png)
![image](https://user-images.githubusercontent.com/17740259/88469809-ba084600-cf27-11ea-8d0f-3569737e9dc3.png)
