### ISSUE TITLE
Quoted strings cause issues

### ISSUE THREAD

**Issue by Timmmm** [go-ini/ini#25]
Consider the following:

    key1 = "value" ; comment
    key2 = "one", "two", "three"

When saved these get mangled to:

    key1 = """"value" ; comment"""
    key2 = """"one", "two", "three""""

Clearly not ideal!

Looking at the parsing code, I think you could *really* do with specifying a formal grammar. [Here is an example.](http://search.cpan.org/~rjbs/Config-INI-0.025/lib/Config/INI.pm#GRAMMAR)

**Comment by Unknwon** [comment]
Good catch.

Also I think the inline comment breaks something indeed...

**Comment by Unknwon** [comment]
OK, just refactored the parser, please try it out.

The save result for 

```ini
key1 = "value" ; comment
key2 = "one", "two", "three"
```

is now

```ini
; comment
key1 = "value"
key2 = "one", "two", "three"
```

**Comment by Timmmm** [comment]
I dunno this still seems like it might not be that robust (though writing a truely robust INI parser is probably impossible).

I decided to modify your library fairly drastically, check it out:

https://github.com/Timmmm/ini/tree/master

You probably don't want to use that because I removed several features I don't need (e.g. variable substitution). But I think my parsing approach is probable better. Here's the approach:

1. Remove multi-line support as this makes it a lot easier (you can still do multiline strings with `"a\nb"`).
2. Add a `modified` boolean to all the keys. This indicates whether they have been modified since loading from disk (or string) (TODO!)
3. When parsing a key (or a section header), only try to split it into the key name, value and comment. In particular I *don't try to parse the value*. To split the comment I use made a couple of functions that find the first *unquoted* character in a string. So for example it you can do:

        letters = "a; b; c"  ; Semicolon separated list of letters.

    Would that break in your parser? Currently the quoting model used is very basic (only double quotes for example). You could add support for `"""` and single quotes.

4. Instead of parsing the values when you load the file, parse them when they are requested. This also has the benefit of allowing users to do their own custom parsing.
5. When writing back to the file, if the value was unmodified write it as-is (also TODO!)

I also added support for trailing comments. Feel free to take any code back!

**Comment by Unknwon** [comment]
> You probably don't want to use that because I removed several features I don't need (e.g. variable substitution). But I think my parsing approach is probable better. Here's the approach:

That's the best thing about open source :wink:

> Remove multi-line support as this makes it a lot easier (you can still do multiline strings with "a\nb").

Thought I agree it is not a commonly used feature, but as a public package remove a feature generally should not happen.

> Add a modified boolean to all the keys. This indicates whether they have been modified since loading from disk (or string) (TODO!)

This is indeed a good thing, this allows you save the config file only for new additions but remain unchanged for everything else.

> When parsing a key (or a section header), only try to split it into the key name, value and comment. In particular I don't try to parse the value. To split the comment I use made a couple of functions that find the first unquoted character in a string. So for example it you can do:

Quotes will be removed is documented explicitly in the README, so it causes break changes.

> Instead of parsing the values when you load the file, parse them when they are requested. This also has the benefit of allowing users to do their own custom parsing.

It should work well in most of cases, but in my personal usages, it hurts big performance (maybe I should say unnecessary cost). For example, I use INI as I18N parse module, it is called so often in when rendering every page.
