### ISSUE TITLE
It is not support go mod?

### ISSUE THREAD

**Issue by vintmd** [go-ini/ini#262]
or If I want to use the go-ini in my project which is go mod, what should I do?

**Comment by unknwon** [comment]
There is no such thing that a Go package "supports" or "not supports" Go Modules. You can just it use, e.g. `gopkg.in/ini.v1`.

**Comment by vintmd** [comment]
env GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build 
go: gopkg.in/ini.v1@v1.51.0: parsing ../gopkg.in/ini.v1/go.mod: open /home/alantong/gospec/src/gopkg.in/ini.v1/go.mod: no such file or directory
@unknwon It always prompt me this which seems like that only can use the ini package when it has mod file?

**Comment by unknwon** [comment]
@vintmd 🤔 Which Go version you're using? I've been using in all kinds of projects enabled Go modules without a single fetching problem.

**Comment by vintmd** [comment]
v1.14

Sent from my iPhone

On Sep 7, 2020, at 21:15, ᴜɴᴋɴᴡᴏɴ <notifications@github.com> wrote:

﻿

@vintmd<https://github.com/vintmd> 🤔 Which Go version you're using? I've been using in all kinds of projects enabled Go modules without a single fetching problem.

**Comment by unknwon** [comment]
Have you used `replace` command in your `go.mod`? Looks like this is the root cause: https://github.com/golang/go/issues/31052

**Comment by vintmd** [comment]
Yes, I remove it from the mod file, it success, thank you for your help

Sent from my iPhone

On Sep 7, 2020, at 21:24, ᴜɴᴋɴᴡᴏɴ <notifications@github.com> wrote:

﻿

Have you used replace command in your go.mod? Looks like this is the root cause: golang/go#31052<https://github.com/golang/go/issues/31052>
