### ISSUE TITLE
1.8.5: test failure "undefined: ShouldBeEmpty"

### ISSUE THREAD

**Issue by onlyjob** [go-ini/ini#27]
I'm getting the following test failure on Debian with Go-1.5.1:

    src/gopkg.in/ini.v1/ini_test.go:495: undefined: ShouldBeEmpty

**Comment by Unknwon** [comment]
Hi, as CI is [passing](https://drone.io/github.com/go-ini/ini/latest), I think you did not use `go get -t xxx` to download dependencies for testing files.

**Comment by onlyjob** [comment]
1. It is unusual to do something like `go get -t xxx` in order to run tests. Form experience I know that most Golang libraries builds and run tests just fine without it. Works with 50+ libraries but not with this one?

2. I build from downloaded tarball _offline_ (in clean chroot) hence I'm unable to `go get`. Please make sure that tarbal is comprehensive and includes all required files to build and to test. At the moment `testdata` directory contains only `conf.ini`.

3. Shall we please refrain from closing bugs right away? There is a problem here and denial do not help... :disappointed: Thanks.

**Comment by Unknwon** [comment]
> It is unusual to do something like go get -t xxx in order to run tests. Form experience I know that most Golang libraries builds and run tests just fine without it. Works with 50+ libraries but not with this one?

Because they use standard lib, I use third-party helper.

> I build from downloaded tarball offline (in clean chroot) hence I'm unable to go get. Please make sure that tarbal is comprehensive and includes all required files to build and to test. At the moment testdata directory contains only conf.ini.

This is because `go get` requires VCS, tarball does not have that.

> Shall we please refrain from closing bugs right away? There is a problem here and denial do not help... :disappointed: Thanks.

I think you're lacking many conventions and knowledge of using Go, you can get more help about this on https://forum.golangbridge.org/ :trollface:

**Comment by Unknwon** [comment]
Added some docs: https://github.com/go-ini/ini#testing

**Comment by onlyjob** [comment]
The problem is that GNU/Linux distributions like Debian or Fedora build packages _offline_.
Build-time downloading is no-no due to security concerns. As we need your package in Debian as a dependency I have to operate within certain constrains.
I am illiterate in Golang but this is not the point. Unfortunately it is typical for Golang to throw away ~20 years of best practice in engineering and bundle ("vendor") unversioned components or download during build...

What do you suggest in order to fix offline build/test of your package?

**Comment by Unknwon** [comment]
> What do you suggest in order to fix offline build/test of your package?

You can download and extract the tarball to `$GOPATH/src/gopkg.in/ini.v1`, then `go get` will just ignore this with a warning, but it can be compiled.

**Comment by onlyjob** [comment]
It builds if I ignore tests but not running tests is wrong! Is there anything you can do to fix it?

**Comment by Unknwon** [comment]
Oh.... I see the problem now..

You can download `github.com/smartystreets/goconvey` and put to its position then do the test.

**Comment by onlyjob** [comment]
Thanks but this is not the problem as _golang-github-smartystreets-goconvey-dev_ is already in package dependencies. Perhaps something else is missing...

**Comment by Unknwon** [comment]
See https://gowalker.org/github.com/smartystreets/goconvey/convey#_variables

**Comment by onlyjob** [comment]
Let me guess, you depend on variable(s) not included into latest _[released version of goconvey](https://github.com/smartystreets/goconvey/releases)_ v1.5.0, right?

**Comment by Unknwon** [comment]
Possible... 1.5.0 was 2 years ago... :scream:

**Comment by onlyjob** [comment]
Yeah... :(  But perhaps it is not ideal when released version of _go-ini_ depends on unreleased/unversioned components... It would be nice to respect [software versioning](https://en.wikipedia.org/wiki/Software_versioning) whenever possible... One of the reasons is that proper versioning allows to define dependencies and reuse shared libraries.

**Comment by Unknwon** [comment]
> Yeah... :( But perhaps it is not ideal when released version of go-ini depends on unreleased/unversioned components... It would be nice to respect software versioning whenever possible... One of the reasons is that proper versioning allows to define dependencies and reuse shared libraries.

Words are always said ideally, but truth is skinny. :dizzy_face:

**Comment by onlyjob** [comment]
It's all simple really. :) 'master' can depend on unreleased stuff but formal releases are better stick to released dependencies whenever possible. Releases suppose to be somewhat more stable, "supported" (whatever it means) and better tested.

**Comment by Unknwon** [comment]
I think you can ask https://github.com/smartystreets/goconvey people to tag a revision.

**Comment by onlyjob** [comment]
Just did that. :)  Thanks for your help, @Unknwon.

**Comment by Unknwon** [comment]
:trollface:

**Comment by onlyjob** [comment]
Goconvey [1.6.0](https://github.com/smartystreets/goconvey/releases/tag/1.6.0) released. :)

**Comment by Unknwon** [comment]
Cool! :100:
