### ISSUE TITLE
key-value delimiter not found for ini file

### ISSUE THREAD

**Issue by gandarez** [go-ini/ini#270]
**Describe the bug**
While parsing an `INI` file where there's a key with multiple lines it throws an error `key-value delimiter not found`.

**To Reproduce**
Create an `INI` with this content
```ini
[git]
submodules_disabled = 
  .*secret.*
  fix.*
```

**Expected behavior**
Should have parsed as a string with line breaks.

**Comment by unknwon** [comment]
Hi, I think you need:

```ini
[git]
submodules_disabled = \
  .*secret.* \
  fix.*
```

Ref: https://ini.unknwon.io/docs/howto/work_with_values

**Comment by gandarez** [comment]
Actually I've been porting a code writen in Python to Go and one of the unofficial features is to support a list simply breaking lines and no "special character" is needed. If I submit a PR to also support it would you mind to include in this library @unknwon ?

**Comment by unknwon** [comment]
@gandarez Yes, adding another field to [`LoadOptions`](https://github.com/go-ini/ini/blob/5e97220809ffaa826f787728501264e9114cb834/ini.go#L69) such as `AllowListWithBreakingLines` (name subject to your change) SGTM :)
