### ISSUE TITLE
how to escase # character

### ISSUE THREAD

**Issue by madneal** [go-ini/ini#277]
**Describe the bug**
The '#' character is always ignore, even use '\#' does not work

**To Reproduce**
Cfg, err = ini.Load(source)

**Expected behavior**
character '#' is not ignored directly

**Comment by uhoh-itsmaciek** [comment]
@madneal I ran into this same issue, the `#` is treated as a comment character. As far as I can tell, there is no way to quote or escape it (see https://github.com/go-ini/ini/issues/187 ), but it looks like you can sort of work around this by passing the [SpaceBeforeInlineComment option](https://gowalker.org/gopkg.in/ini.v1#LoadOptions), like this:

```golang
Cfg, err := ini.LoadSources(ini.LoadOptions{SpaceBeforeInlineComment: true}, source)
```

This will mean that entries like

```ini
key=value_with_#_in_it
```

are parsed correctly. Entries like

```ini
key=value with # in it
```

will still be cut off (note the spaces).

**Comment by madneal** [comment]
@uhoh-itsmaciek Thanks a lot. It does help me.
