### ISSUE TITLE
Add support for go modules

### ISSUE THREAD

**Issue by domust** [go-ini/ini#278]
**Is your feature request related to a problem? Please describe.**

Hi,  am using Go 1.15.5 and I would like to add this library as a dependency for my project.

**Describe the solution you'd like**

Adopt https://blog.golang.org/using-go-modules

**Describe alternatives you've considered**

**Additional context**

I can do the work, just let me know the module name.

**Comment by asciifaceman** [comment]
Looks abandoned, since posting have you found an actively supported and up to date ini file parser?

**Comment by unknwon** [comment]
This package can't have Go Modules because Go Modules do not allow two different import paths. This package has been widely referenced by both `gopkg.in/ini.v1` and `github.com/go-ini/ini`.

Once there is a change to release v2, then we can have Go Modules.
