### ISSUE TITLE
can't parse “#”  

### ISSUE THREAD

**Issue by Boblis** [go-ini/ini#282]
**Describe the bug**
when I use the go-ini package parse the ini config file , but it can't parse the character “#” 

for example：
It parse the password failed, the password contain the character "#"

![image](https://user-images.githubusercontent.com/45844993/106087887-e2376280-615f-11eb-9d54-452cd536a999.png)
my password is test123456#@, but it parse it to test123456

**Comment by canghai908** [comment]
allso have this problem.

**Comment by Boblis** [comment]
No ，python package can do it，I had tried，It can work well


发自我的iPhone

------------------ Original ------------------

**Comment by Mosslar** [comment]
use ``

Password = `test123456#@`

**Comment by canghai908** [comment]
> use ``
> 
> ```
> Password = `test123456#@`
> ```

Thank you，it works well.

**Comment by 5nafu** [comment]
@unknwon, please reopen this issue. 
Using backticks (as mentioned by @Mosslar, thanks you for the hint) might work in some applications, but will fail for example for parsing an `aws_config`.

We do have an `sso_start_url` in the following format:
```
sso_start_url  = https://company.awsapps.com/start#/
```
and the aws cli does not like this to be quoted. I tried backticks `` ` ``, single `'`   and double quotes `"`.

Similar to what is mentioned in iann0036/iamlive#25

**Comment by unknwon** [comment]
@5nafu You can ignore inline comments altogether: https://ini.unknwon.io/docs/howto/work_with_comments
