### ISSUE TITLE
Using dots in config keys as separators

### ISSUE THREAD

**Issue by ahmetalpbalkan** [go-ini/ini#29]
Hi, I'm trying to parse a config file that looks like this:

```
Foo.A = value
Foo.B = value
C = value
```

into a struct such as

```
type Configuration struct {
    Foo struct {
        A string
        B string
    }
    C string
} 
```

However it looks like in order to have a struct like this, my config file needs to be like:

```
C=...
[Foo]
A=...
B=...
```

but it is not. So, is there a way to configure the library or my struct to work the way I am trying? Or is it not possible with the existing code?

**Comment by Unknwon** [comment]
Which section are these keys in? Default?

```ini
Foo.A = value
Foo.B = value
C = value
```

**Comment by ahmetalpbalkan** [comment]
Yes. This file doesnt use sections, so default is the only section.

**Comment by Unknwon** [comment]
OK, according to https://github.com/go-ini/ini#other-notes-on-mapreflect and https://github.com/go-ini/ini/blob/master/ini.go#L33, you can see:

```go
type Configuration struct {
    Foo struct {
        A string
        B string
    } `ini:"DEFAULT"`
    C string
} 
```

**Comment by ahmetalpbalkan** [comment]
@Unknwon thanks.

**Comment by Unknwon** [comment]
:trollface:
