### ISSUE TITLE
Project referencing itself with gopkg.in/ini.v1 causes double entries in the go mod file. 

### ISSUE THREAD

**Issue by myusuf3** [go-ini/ini#292]
**Describe the bug**
We are seeing weird import paths for a dependencies that uses this project. Looks like go mod doesn't ignore test files when we are building the dependency graph. 

We are seeing the following

``` go
go mod why gopkg.in/ini.v1
# gopkg.in/ini.v1
github.com/aws/aws-sdk-go/aws/session
github.com/go-ini/ini
github.com/go-ini/ini.test
gopkg.in/ini.v1
```

As you can see the dependency chain ends correct here. 

```go
go mod why github.com/go-ini/ini
# github.com/go-ini/ini
github.com/aws/aws-sdk-go/aws/session
github.com/go-ini/ini
```

**To Reproduce**
Simply rely on go-ini/ini and run a go mod tidy and see two imports for the same project. 

**Expected behavior**
We should only see one import for the dependency.

**Comment by unknwon** [comment]
Good catch!

**Comment by unknwon** [comment]
You may pull down https://github.com/go-ini/ini/releases/tag/v1.63.2, which should no longer have "gopkg.in/ini.v1" in your dependency tree.
