### ISSUE TITLE
github.com/smartystreets/goconvey v1.6.4 // indirect

### ISSUE THREAD

**Issue by zqfan** [go-ini/ini#295]
please remove indirect test dependency from product code

**Comment by sagikazarmark** [comment]
Unfortunately this is not an indirect dependency, it is actively used throughout the library.

Looking at the dependency tree that goconvey pulls in, it seems to me that both goconvey and its transitive dependencies are abandoned or barely developed at this point which is sad.

I also thing that getting rid of the heavy dependencies would be nice. There are a couple solutions I can think of:
- Sending a patch to goconvey to either get rid of the gls library usage or replace it with a different lib that doesn't depend on gopherjs (see jtolio/gls#15)
- Drop goconvey from the tests and use only the go test framework with testify for assertions

**Comment by unknwon** [comment]
I generally agree on what @sagikazarmark has said, and would love fully migrate to `testify`.

**Comment by sagikazarmark** [comment]
@unknwon please see the referenced PR.

**Comment by zqfan** [comment]
Thanks!
