### ISSUE TITLE
Support loading config which does not have values.

### ISSUE THREAD

**Issue by elonzh** [go-ini/ini#305]
**Is your feature request related to a problem? Please describe.**

See [Python ConfigParser](https://docs.python.org/3/library/configparser.html#:~:text=foo%27%2C%20%27bar%27%2C%20%27baz%27%5D-,allow_no_value,-%2C%20default%20value%3A%20False)

> Some configuration files are known to include settings without values, but which otherwise conform to the syntax supported by configparser. The allow_no_value parameter to the constructor can be used to indicate that such values should be accepted

**Describe the solution you'd like**

Works like python ConfigParser. Add a LoadOptions such `AllowNoValue`.

**Comment by unknwon** [comment]
I think this is what you're looking for: https://ini.unknwon.io/docs/howto/work_with_keys#mysql-like-boolean-key
