### ISSUE TITLE
value中不能包含#，#后面的无法解析

### ISSUE THREAD

**Issue by cheenwe** [go-ini/ini#318]
### Version

v1.66.4

### Describe the bug

比如我有个密码参数： password = "deploy#2022"
只能读取到 "deployer

### To reproduce

![image](https://user-images.githubusercontent.com/5643208/158061178-2d08d349-4561-4366-a691-aaddbcbffe49.png)

### Expected behavior

无

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by unknwon** [comment]
Duplicated to https://github.com/go-ini/ini/issues/282.
