### ISSUE TITLE
Parser should respect quoted or escaped delimiter

### ISSUE THREAD

**Issue by marcopaganini** [go-ini/ini#32]
If we have a field defined as a slice and using space as a delimiter, say:

```
ExtraArgs   []string `ini:"extra_args" delim:" "`
```

An entry in the ini file formatted as:
```
extra_args = aaa bbb ccc
```

Correctly generates a slice of three string elements, "aaa", "bbb", and "ccc".

However, things get complicated if we need one of the elements to contain a space. I tried the following constructs without success:

```
extra_args = aaa "bbb and space" ccc

extra_args = aaa bbb\ and\ space ccc

extra_args = """
aaa
bbb and space
ccc"""
```

And neither seems to work.

Ideally, the delimiter shouldn't be matched inside quoted strings of it it's quoted with a backslash.

**Comment by Unknwon** [comment]
Thank your feedback!

It is indeed a problem... but why can you just use `,` :trollface:

**Comment by marcopaganini** [comment]
Oh,  but then we'd have the same problem with the comma, no? :)
The fact is, unless we allow quoting or escaping, there will always be one
character we can't use (the delmiter).

**Comment by Unknwon** [comment]
If you have `,`, then use `,,`, then `,,,`, and `,,,,`, etc...
