### ISSUE TITLE
Panic when submitting non-existing files to Load()

### ISSUE THREAD

**Issue by alessio** [go-ini/ini#33]
Hi,

I'm submitting a slice of three files to `ini.Load()`:

```go
cfg, err := ini.Load("/etc/securepass.conf", "/usr/local/etc/securepass.conf", "securepass.conf")
```

Only the latter exists and has the correct permissions set. Likewise the Python `ConfigParser` module, it would be great if the function could read the configuration from only those accessible or return an empty configuration if no existing files were provided.

```console
$ ~/go/src/github.com/garlsecurity/go-securepass$ go run spctl/main.go 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4811b2]

goroutine 1 [running]:
gopkg.in/ini%2ev1.(*File).GetSection(0x0, 0x7fa130, 0x7, 0x0, 0x0, 0x0)
	/home/SMARTODDS/tregliaa/go/src/gopkg.in/ini.v1/ini.go:976 +0x72
main.loadConfiguration()
	/home/SMARTODDS/tregliaa/go/src/github.com/garlsecurity/go-securepass/spctl/main.go:50 +0xc2
main.main()
	/home/SMARTODDS/tregliaa/go/src/github.com/garlsecurity/go-securepass/spctl/main.go:60 +0x1c

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
exit status 2
```

Thanks for considering.

**Comment by alessio** [comment]
Currently I'm relying on this workaround:
```go
	cfg := ini.Empty()
	for _, filename := range SystemConfigFiles {
		if fp, err := os.Open(filename); err == nil {
			fp.Close()
			cfg.Append(filename)
		}
	}
```

**Comment by Unknwon** [comment]
I think you get panic because you did not check every returned error.

Please post more complete code in order to debug.

**Comment by alessio** [comment]
I have no way check the return values as the `Load()` call fails.

**Comment by Unknwon** [comment]
Thanks, but do no skip my comments:

> Please post more complete code in order to debug.

**Comment by alessio** [comment]
My apologies, you were right, I didn't check the error returned by `Load()`.
Though I was expecting a different behaviour:
```go
package main

import (
	"github.com/go-ini/ini"
	"fmt"
)


func main() {
	_, err := ini.Load("existing-file.ini", "non-existing-file.ini")
  	if err != nil {
		fmt.Println("%v", err)
	}
}
```

As the name suggests, __existing-file.ini__  is an existing configuration file. By contrast, __non-existing-file.ini__ is a path to a non-existent file. Although the program could open an access the former, `Load()` returns an error because it can't open the latter too.
I'd expect my program to load the configuration from at least those files that exist and can be opened successfully. This is a common practice when you develop applications that allow the user to override/extend program's settings by override _system-wide_ config files placed typically under `/etc` with _site-specific_ ones (e.g. `/usr/local/etc`) or user-specific files generally stored in the user's home directory.

Apparently this is not a bug per se` then, though I'd suggest to either:

1. Document the `Load()` semantics more clearly by informing the client that he must take the responsibility to check whether the filenames can be opened successfully.
2. Create a new `SafeLoad()` wrapper similar to [Python's RawConfigParser.read()](https://docs.python.org/2/library/configparser.html#ConfigParser.RawConfigParser.read) method that tries opening all files given as parameters, skips all those which it cannot open, and falls back to an empty configuration if it can't load any data.

If you were happy to go for 2., I'd be willing to allocate some time to develop a solution and file a PR.

**Comment by Unknwon** [comment]
Good to know the real problem!

> Document the Load() semantics more clearly by informing the client that he must take the responsibility to check whether the filenames can be opened successfully.

It is always the convention that do not ignore any returned errors in Go, skip error checking is already wrong, everything after that then become pointless.

> Create a new SafeLoad() wrapper similar to Python's RawConfigParser.read() method that tries opening all files given as parameters, skips all those which it cannot open, and falls back to an empty configuration if it can't load any data.

I suggest we do the another way around, instead of change behavior of `Load`, we add new method with unsafe load, but I can't think of a short and good name for it.

**Comment by alessio** [comment]
> It is always the convention that do not ignore any returned errors in Go,
> skip error checking is already wrong, everything after that then become pointless.

I definitely agree, nonetheless adding a a brief note saying "beware that the function fails even if it can't load only 1 out N parameters" wouldn't do any harm I guess. Thanks very much for considering though :)

> I suggest we do the another way around, instead of change behavior of Load,
> we add new method with unsafe load, but I can't think of a short and good name for it.

Agreed, that is exactly what I meant to propose: create a new function to avoid breaking the interface of `Load()` as many programs have already been developed using go-ini. Regarding the new function's possible name, I was thinking about some names such as `Read()`, `ReadFromFiles` or `ReadFiles`. As I said, I'd be happy to take this and prepare a PR.

**Comment by Unknwon** [comment]
> Agreed, that is exactly what I meant to propose: create a new function to avoid breaking the interface of Load() as many programs have already been developed using go-ini. Regarding the new function's possible name, I was thinking about some names such as Read(), ReadFromFiles or ReadFiles. As I said, I'd be happy to take this and prepare a PR.

Of course, how about `LooseLoad`?

**Comment by Unknwon** [comment]
Then you can add a private field `looseMode` here: https://github.com/go-ini/ini/blob/master/ini.go#L114

So parser knows if it should check file existence first before loading the data.

**Comment by Unknwon** [comment]
Pushed an update for your PR.

**Comment by alessio** [comment]
Nice one, thanks!

On Mon, Feb 22, 2016 at 9:17 PM, 无闻 <notifications@github.com> wrote:

> Pushed an update for your PR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/go-ini/ini/issues/33#issuecomment-187387335>.
>



-- 
Alessio Treglia          | www.alessiotreglia.com
Debian Developer         |     alessio@debian.org
Ubuntu Core Developer    |  quadrispro@ubuntu.com
0416 0004 A827 6E40 BB98 90FB E8A4 8AE5 311D 765A

**Comment by Unknwon** [comment]
Docs are added: https://github.com/go-ini/ini/tree/v1.10.0#loading-from-data-sources

**Comment by alessio** [comment]
Looks good :+1:

On Mon, Feb 22, 2016 at 9:27 PM, 无闻 <notifications@github.com> wrote:

> Docs are added:
> https://github.com/go-ini/ini/tree/v1.10.0#loading-from-data-sources
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/go-ini/ini/issues/33#issuecomment-187390710>.
>



-- 
Alessio Treglia          | www.alessiotreglia.com
Debian Developer         |     alessio@debian.org
Ubuntu Core Developer    |  quadrispro@ubuntu.com
0416 0004 A827 6E40 BB98 90FB E8A4 8AE5 311D 765A

**Comment by alessio** [comment]
Unfortunately this still needs some work as I've managed to trigger an actual panic:
```go
// LoadConfiguration reads configuration from files
func LoadConfiguration(conffiles []string) error {
	files := make([]interface{}, 0, len(conffiles))
	for _, fn := range conffiles {
		files = append(files, fn)
	}
	cfg, err := ini.LooseLoad(files[0], files[1:]...)
	fmt.Println(err)
	defaultSection, _ := cfg.GetSection("default")
	nssSection, _ := cfg.GetSection("nss")
	sshSection, _ := cfg.GetSection("ssh")
	Service = &securepass.SecurePass{Endpoint: securepass.DefaultRemote}
	NSSSettings = &securepass.NSSConfig{
		DefaultGid:   100,
		DefaultHome:  "/home",
		DefaultShell: "/bin/bash",
	}
	SSHSettings = &securepass.SSHConfig{}
	if err := defaultSection.MapTo(Service); err != nil {
		return err
	}
// continues ...
```

```console
$ ./spctl config --stdout
<nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x511539]

goroutine 1 [running]:
panic(0x805ee0, 0xc82000e120)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
gopkg.in/ini%2ev1.(*Section).GetKey(0x0, 0x895aa5, 0x6, 0x895aa5, 0x0, 0x0)
	/home/alessio/go/src/gopkg.in/ini.v1/section.go:67 +0x39
gopkg.in/ini%2ev1.(*Section).mapTo(0x0, 0x819040, 0xc82000b260, 0x199, 0x0, 0x0)
	/home/alessio/go/src/gopkg.in/ini.v1/struct.go:199 +0x488
gopkg.in/ini%2ev1.(*Section).MapTo(0x0, 0x85c960, 0xc82000b260, 0x0, 0x0)
	/home/alessio/go/src/gopkg.in/ini.v1/struct.go:219 +0x1d7
github.com/garlsecurity/go-securepass/securepass/spctl/service.LoadConfiguration(0xc82004df10, 0x3, 0x3, 0x0, 0x0)
	/home/alessio/go/src/github.com/garlsecurity/go-securepass/securepass/spctl/service/service.go:38 +0x4e4
main.init.1()
	/home/alessio/go/src/github.com/garlsecurity/go-securepass/securepass/spctl/main.go:30 +0x1c4
main.init()
	/home/alessio/go/src/github.com/garlsecurity/go-securepass/securepass/spctl/main.go:52 +0x5e
```

Note that the error returned by `ini.LooseLoad()` is `nil`, `defaultSection.MapTo()` panics afterwards.

**Comment by Unknwon** [comment]
OK, pushed another fix.

However, your problem here is because you skip checking errors, which all your sections are `nil` as I can tell.

**Comment by alessio** [comment]
I deliberately skipped the errors this time as in loose mode I'd expect the sections to be empty if I tried to retrieve them. Your fix works fine, thanks!
