### ISSUE TITLE
Case insensitive ini keys

### ISSUE THREAD

**Issue by gpaterno** [go-ini/ini#36]
Please support case insensitive keys and sections in an ini file, ex: via an option.
ex: treat "FOO = bar" like "foo = bar" or "Foo = bar".
Thanks

**Comment by Unknwon** [comment]
Hi, can you give an example use of this feature?

**Comment by gpaterno** [comment]
Sure. Sometimes keys are written by users in mixed case format, even if you specify in the docs that have to be lowercase. So that, you can have in ini file:

FOO = bar
Foo = bar
foo = bar

Would be able to retrieve the same value using case insensitive key retrieval.
Hope that I was able to express myself :(
Thanks.

**Comment by Unknwon** [comment]
Thanks, so there is one problem left, inside the library, all key names will be stored as in lower cases. Therefore if you want to write out them, output format will have all lowercase key names.

Does this sound OK to you?

**Comment by gpaterno** [comment]
Apologies for the long-waiting answer.
Yes! The most problematic is the read .... as much as you can specify and tell hard the user to watch out how they write by hand the .ini file, they will use mixed cases. :(
Thanks.

**Comment by Unknwon** [comment]
Example:

```go
cfg, err := ini.InsensitiveLoad("filename")
//...

// sec1 and sec2 are the exactly same section object
sec1, err := cfg.GetSection("Section")
sec2, err := cfg.GetSection("SecTIOn")

// key1 and key2 are the exactly same key object
key1, err := cfg.GetKey("Key")
key2, err := cfg.GetKey("KeY")
```
