### ISSUE TITLE
Explicit DEFAULT section when writing to file

### ISSUE THREAD

**Issue by nextrevision** [go-ini/ini#37]
Currently, when adding/modifying a key in the `DEFAULT` section, there is no way to explicitly write the section name. For example, if I had an existing file, config.ini:

```
[DEFAULT]
key1 = value1

[another_section]
another_key = another_value
```

If I modified `key1` like so:

```
cfg, _ := ini.Load("config.ini")
key := cfg.Section("DEFAULT").Key("key1")
key.SetValue("value2")
cfg.SaveTo("config.ini")
```

This would strip the explicit `[DEFAULT]` section name from the file, resulting in:

```
key1 = value2

[another_section]
another_key = another_value
```

It would be great to have the ability to specify including the explicit `DEFAULT` section header.

**Comment by Unknwon** [comment]
Hi, in my understanding, key-value pairs start without any section, are all belonging to so-called default section.

**Comment by nextrevision** [comment]
The OpenStack projects, for example, look for that section and, in my experience, fail if the `[DEFAULT]` header is not explicitly stated.

**Comment by Unknwon** [comment]
OK... that is sad... let me see what I can do..
