### ISSUE TITLE
Support other boolean values

### ISSUE THREAD

**Issue by henryx** [go-ini/ini#4]
Currently, library support "true or false" for boolean values. It is a good idea to extend the support for "yes or no" and "on or off" values

**Comment by Unknwon** [comment]
Package uses standard to parse bool value: https://gowalker.org/strconv#ParseBool , including `1, t, T, TRUE, true, True, 0, f, F, FALSE, false, False`, I think those are enough.

But if you have strong OCD on supporting "on" and "off", I can support it.

Any thoughts?

**Comment by henryx** [comment]
"on" and "off" (or "yes" and "no") are more comprehensive in some cases, for example
`
[archive]
tarfile = true
compression = on
xz = yes
`

**Comment by Unknwon** [comment]
Cool, make sense to me. I'll do it :blush:

**Comment by Unknwon** [comment]
Hi, I've extended boolean values as follows:

// true when value is: 1, t, T, TRUE, true, True, YES, yes, Yes, ON, on, On
// false when value is: 0, f, F, FALSE, false, False, NO, no, No, OFF, off, Off
