### ISSUE TITLE
string with too many zeros?

### ISSUE THREAD

**Issue by dubyte** [go-ini/ini#40]
I dont know if this is expected but when do: (imagine we have a value that prints "2")

```
 r := key.Value()
fmt.Println(r) //The result is "2"

//If I compare r with "2"
if r == "2" {
//This never happen because misteriously r and "2" are defferent despite both print the same value.
}
```
so I noticed that when I do len(r) is like 958
but len("2") is 1

so if I do fmt.Println([]byte(r))
it prints something like
[50 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 ... 0]

edit: actually was a problem in my code while using a buffer. But I can't delete an issue

**Comment by dubyte** [comment]
I did this:

strings.Trim(k.Value(), "\x00")

But dont know whether is expected that I need to do it

**Comment by dubyte** [comment]
nvm, was my error at the moment of adding the config from a buffer.

**Comment by Unknwon** [comment]
So.... what is the expectation from you?

**Comment by dubyte** [comment]
Hello Unkwon:

I was expecting that when you compare two strings that print the same value, but one of them actually have a lot of trailing zeros, the result was true.

But after search about this issue, the quick answer was that go is not C, and for Go is totally different a string with "2" and "2" + "\x000".

So I think there is nothing todo in INI itself.

So I try to trim the result, but later, a friend recommended me to write in a buffer **only the number of characters** that I read from a file.

And that was actually what I was doing wrong. And INI was just behaving as expected.

Thanks for your time.

**Comment by Unknwon** [comment]
:trollface:
