### ISSUE TITLE
Ignoring continuation character

### ISSUE THREAD

**Issue by mar1ged** [go-ini/ini#44]
I use go-ini for reading .ini files of a Windows application. Unfortunately the developer of that application decided to store pathnames with trailing backslashes:

```
[Directories]
SourceDir=C:\App\Source\
TargetDir=C:\App\Target\
```

When I read `SourceDir` I receive the value `C:\App\SourceTargetDir=C:\App\Target\` because the `\` gets treated as a continuation char.
Is it possible to tell the library _not_ to handle the continuation char ? Unfortunately I can not change the ini files content because this breaks the application (which was not written by me and can not be changed by me)

**Comment by Unknwon** [comment]
Now you're able to use:

```go
cfg, err := ini.LoadSources(ini.LoadOptions{IgnoreContinuation: true}, xxx)
```
