### ISSUE TITLE
Values not saved with «ini.SaveTo(iniFilePath string)»

### ISSUE THREAD

**Issue by vadeva** [go-ini/ini#45]
When saving with ini.saveTo() the target file is created or replaced succesfully. However, it contains proper section names and keys, but all the values are missing. 

I have verified the values contain data by performing fmt.Printf output right before calling ini.saveTo()

Platform: Go 1.6.1, Mac OS 10.11.4

This is how the contents look like:
![2016-04-27 18 02 05](https://cloud.githubusercontent.com/assets/18702939/14856805/38e76d22-0ca2-11e6-83fc-9873e3b2ff44.png)

**Comment by vadeva** [comment]
I have found the reason, sorry.

The ini.Key(<key_name>).Must*(<default_value>) methods do NOT set the value of the key to default one. 

Such behauviour is very inobvious... 
1) ini.Key(<key_name>) creates the key if it does not exist
2) However, the default value is not with Must* method
One ends up with an always existing key, but it may have no value!

**Comment by Unknwon** [comment]
>2) However, the default value is not set with a Must* method.
One ends up with an always existing key, but it may have no value!

Good point!

**Comment by Unknwon** [comment]
Changes pushed.
