### ISSUE TITLE
Parsing non-string arrays from struct fails

### ISSUE THREAD

**Issue by silasray** [go-ini/ini#48]
The struct parser does not cast types when constructing a slice to assign to a field, so it fails with a type error on assignment.

**Comment by Unknwon** [comment]
Hi, can you give an example?

**Comment by silasray** [comment]
The problem is https://github.com/go-ini/ini/blob/master/struct.go#L154

If the element type is not reflectTime (which is actually structtype, which is another problem...), it defaults to dumping out vals with the type of vals elements, which is string.  This needs to make use of the <type>s methods of key, based on the type of the formatting struct.

**Comment by Unknwon** [comment]
I might know what you're trying to say, maybe provide a real example will be more helpful?

**Comment by silasray** [comment]
```package main

import "fmt"
import "github.com/go-ini/ini"


type Stringy struct {
	Strings []string
}

type Numy struct {
	Nums []int
}

func main() {
	// Works fine
	conf, _ := ini.Load([]byte("Strings=1,2,3"))
	stringy := new(Stringy)
	err := conf.MapTo(stringy)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(stringy.Strings)

	// Panics in reflect.Set at struct.go#154
	// trying to assign string to int
	conf, _ = ini.Load([]byte("Nums=1,2,3"))
	numy := new(Numy)
	err = conf.MapTo(numy)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(numy.Nums)
}```

**Comment by Unknwon** [comment]
Hi, please update the package and re-test.

**Comment by silasray** [comment]
Yup, works.
