### ISSUE TITLE
continuation lines

### ISSUE THREAD

**Issue by makuk66** [go-ini/ini#5]
Feature request for continuation lines as described in http://en.wikipedia.org/wiki/INI_file#Escape_characters, for example:

    [section]
    args=looong \
      line

**Comment by Unknwon** [comment]
Good catch! Working on it now.

**Comment by Unknwon** [comment]
Hi @makuk66 , I've pushed code to support continuation lines, please help test! Thanks.

**Comment by Unknwon** [comment]
Close it for now as implemented, welcome to continue discussion when you found bug! :beer:
