### ISSUE TITLE
Handle boolean values

### ISSUE THREAD

**Issue by RichiH** [go-ini/ini#53]
For details, see https://github.com/prometheus/mysqld_exporter/issues/132

**Comment by Unknwon** [comment]
Hi, so for those boolean keys, the value of them are defaults to `true`?

**Comment by RichiH** [comment]
@Unknwon Sorry, I missed that question back then... Pliease re-open for now.

@bastischubert should have more details on this issue.

**Comment by RichiH** [comment]
@Unknwon thanks!

**Comment by bastischubert** [comment]
ther's no value for a key like "skip-name-resolve" in my.cnf, it's just the existance of the key thats needed for the my.cnf ;)

**Comment by RichiH** [comment]
@Unknwon Yes, it's implicitly set to `true`.

**Comment by Unknwon** [comment]
https://github.com/go-ini/ini#mysql-like-boolean-key
