### ISSUE TITLE
Sections should work with maps, maybe.

### ISSUE THREAD

**Issue by henvic** [go-ini/ini#54]
I understand maps (say, map[string]interface{}) are currently not supported to automagically translate to sections.

I have two questions:
1. Have you considered it?
2. Do you find it a great idea?
3. If you do, do you intend to add support to this or are open to pull requests on this?

I have taken a quick look at setWithProperType and reflectWithProperType and it seems not to be so hard to do so, so maybe there is a good reason why it wasn't done on the first place (maybe because there were priorities and the delimiter didn't make it trivial?).

* not that it is difficult to workaround this situation right now as you can just add it later like that:

```go
cfg.Section("remotes").KeyHashs()
```

btw, I love the simplicity of this library. Well done! Keep up the good work!

**Comment by Unknwon** [comment]
Hi,

>I understand maps (say, map[string]interface{}) are currently not supported to automagically translate to sections.

This part I do not quite understand? Would you mind give an example?

**Comment by henvic** [comment]
See how I work around remotes in https://github.com/wedeploy/cli/blob/504302f5bef37b1c0c3547cb66642e2314b7b63c/config/config.go#L164-L192 (and also, the updateRemotes method) for the configuration file https://github.com/wedeploy/cli/blob/3bdf0fdfb0b24281f61f0519f95ffd1b74dd9d72/config/mocks/remotes/.we

I think it'd be nice to recreate sections automatically, like they were maps or something.

**Comment by Unknwon** [comment]
OK, so you're trying give a `map`, and want library create a section for you?

**Comment by henvic** [comment]
I wanted to do something like this:

configuration:
```ini
NAME = Unknwon
Male = true
Age  = 21
GPA  = 2.8

[Embeded]
Dates  = 2016-06-30T11:57:46-03:00
Places = HangZhou
None   =
```

code:
```go

package main

import (
	"fmt"

	"gopkg.in/ini.v1"
)

type Embeded map[string]string

type Author struct {
	Name      string `ini:"NAME"`
	Male      bool
	Age       int
	GPA       float64
	NeverMind string `ini:"-"`
	*Embeded
}

var expected = map[string]string{
	"Dates":  "2016-06-30T11:57:46-03:00",
	"Places": "HangZhou",
}

func main() {
	var cfg, err = ini.Load("foo.ini")

    if err != nil {
        panic(err)
    }

    var v Author
    fmt.Println("Expected v.Embeded to be", expected)

    err = cfg.MapTo(&v)

    if err != nil {
        panic(err)
    }

    fmt.Println(v.Embeded)
}

```

Maybe not only take map[string]string, but map[string]interface, so it could it would work on arrays, for example.

**Comment by Unknwon** [comment]
So you want map section to a `map`?
