### ISSUE TITLE
Allow omitting empty keys

### ISSUE THREAD

**Issue by radeksimko** [go-ini/ini#59]
The default golang JSON (un)marshal implementation respects `omitempty` inside a field's tag which will effectively omit such field from the resulting JSON if it's not defined in a given struct.

```go
Field int `json:"myName,omitempty"`
```

I was wondering if there's any interest in such feature for this library - i.e. support something like this:

```go
type Profile struct {
	First  string `ini:"first"`
	Second string `ini:"second,omitempty"`
}
```

The current implementation doesn't interpret commas in any special way which results in the following output:

```ini
[my-section]
first            = custom-value
second,omitempty = 
```

The expected behaviour would be

```ini
[my-section]
first = custom-value
```

Is there any reason to support commas inside key names? 😺

**Comment by Unknwon** [comment]
Sounds good, feel free to send PR.

**Comment by radeksimko** [comment]
See #60
