### ISSUE TITLE
I write a "true" in ini file,but the result of read is "false"

### ISSUE THREAD

**Issue by iazkaban** [go-ini/ini#6]
I write a "true" in ini file,but the result of read is "false"

**Comment by iazkaban** [comment]
I find this problem in gogs,the ini file "conf/app.ini"

**Comment by Unknwon** [comment]
If you write `true` and it is true by test cases: https://github.com/go-ini/ini/blob/v1/ini_test.go#L64 .

In your case, I think you change the wrong file.
