### ISSUE TITLE
how to support sections with same name

### ISSUE THREAD

**Issue by ryanking8215** [go-ini/ini#63]
i.e.

``` ini
[entry]
id=1
entry_attr1=a
entry_attr2=b

[entry]
id=2
entry_attr1=c
entry_attr2=d
```

It seems go-ini doesn't support this situation. it always gets the last one of them. Or there is another way to solve this?

**Comment by Unknwon** [comment]
Hi, you can use different name for them to solve the problem :)

**Comment by meroujanantonyan** [comment]
Hello, im trying to make an web interface for Wireguard and i need to write multiple sections with the same name "Peer". Is there any chance to implement this functionality ? 
Thank you

**Comment by unknwon** [comment]
@meroujanantonyan I'll reopen this issue as feature request, but no plan in the near future.

**Comment by mritd** [comment]
same problem...

**Comment by unknwon** [comment]
Merge this issue into https://github.com/go-ini/ini/issues/190.
