### ISSUE TITLE
supporting duplicate sections

### ISSUE THREAD

**Issue by seiko2plus** [go-ini/ini#74]
I already made a simple solution but it doesn't work with Test_Key() , please check my pull request

**Comment by Unknwon** [comment]
Hi! What is the purpose and use case of this feature?

**Comment by seiko2plus** [comment]
Duplicate sections is really important to dynamically define some kind of configurations like multi databases, hosts, users, etc.

Maybe it should be an option disabled by default, since preferred is overriding.

Examples
[database]
engine=mysql
;........

[database]
engine=sqlite
;........

;--------------------------------------
[sudoer]
user=one
;......

[sudoer]
user=two
;......

[sudoer]
user=three
;......

;--------------------------------------
[server]
host=domain1.com
;......

[server]
host=domain2.com
;......

**Comment by Unknwon** [comment]
I think you should really use [TOML](https://github.com/toml-lang/toml).

**Comment by seiko2plus** [comment]
I think so. Thanks.
