### ISSUE TITLE
感觉用结构体读取分区下的k,v很麻烦啊，每个都要申明一个结构体。。

### ISSUE THREAD

**Issue by zouhuigang** [go-ini/ini#76]
能不能不申明结构体，直接转换成map，这样就能动态的添加字段了。?

**Comment by Unknwon** [comment]
这个不能满足需求吗。。

```go
hash := cfg.Section("").KeysHash()
```

**Comment by iTanken** [comment]
> 这个不能满足需求吗。。
> 
> ```go
> hash := cfg.Section("").KeysHash()
> ```

这个是获取  `ini to map`，他要的应该是通过 map 转成 ini `map to ini`
