### ISSUE TITLE
boolean keys do not get sanitised from the \n

### ISSUE THREAD

**Issue by zeph** [go-ini/ini#78]
i was able only to provide a proper unit test for it until now https://github.com/go-ini/ini/pull/77

![convey](https://cloud.githubusercontent.com/assets/209808/21263285/300a9dea-c396-11e6-940f-57a6be93634c.png)

**Comment by zeph** [comment]
I provided a working patch too! :)

**Comment by Unknwon** [comment]
Hi! I'm not quite understand the purpose and use case of this issue... can you explain more?

**Comment by zeph** [comment]
Hi @Unknwon ,
this is needed to handle sections like this in the INI files
```
[section]
key1
key2
#key3
key4
```
currently, even though you implemented the booleanKeys parser option,
if you try to cfg.Section("section").KeyStrings() you receive the listKey structure, but
it is malformed, as each kname has not be stripped out of the trailing \n

**Comment by zeph** [comment]
check the files in the pull request https://github.com/go-ini/ini/pull/77

**Comment by Unknwon** [comment]
Commented on the PR.

**Comment by zeph** [comment]
merged, closing
