### ISSUE TITLE
Section("")不能选择默认分区

### ISSUE THREAD

**Issue by dxvgef** [go-ini/ini#8]
ini文件里有个[default]分区，但是用Section("")获取不到

**Comment by Unknwon** [comment]
Hi, for example:

```ini
NAME = Unknwon
Age = 21
Male = true
Money = 1.25
Born = 1993-10-07T20:17:05Z

[Others]
Cities = HangZhou|Boston
Visits = 1993-10-07T20:17:05Z, 1993-10-07T20:17:05Z
Note = Hello world!
```

The block:

```ini
NAME = Unknwon
Age = 21
Male = true
Money = 1.25
Born = 1993-10-07T20:17:05Z
```

is what so-called `default` section, and can be accessed by `Section("")`.

In your case, `[default]` is not the real default section, should use `Section("default")`.

**Comment by gzliudan** [comment]
请问怎样区分 cfg.GetSection("") cfg.GetSection("default") 这2个不同的小节呢？他们的Name() 都是default

**Comment by Unknwon** [comment]
Default section is `DEFAULT`, not `default`, and if your name a section `DEFAULT`, they will be treated as one.
