### ISSUE TITLE
read me does not contain a full example

### ISSUE THREAD

**Issue by fastfading** [go-ini/ini#80]
I search on google , this ini package has the most stars.
But it did not have a full example
and no test data ini.
User can hardly use this lib since there is no example

**Comment by Unknwon** [comment]
What is a "full example"?

I don't understand...

**Comment by fastfading** [comment]
完整的例子，就是给出一个 ini 的example    ，   然后列举代码解析。
作为首次使用的用户，readme 确实难懂了一些。
如果有个例子可能更好理解。
我google go ini 这是google 第一个推荐的。
如果能方便用户，相信以后会更好。谢谢


2016-12-21 19:13 GMT+08:00 无闻 <notifications@github.com>:
