### ISSUE TITLE
Support Array/map value read

### ISSUE THREAD

**Issue by fastfading** [go-ini/ini#81]
ini example 
[BG 0]
spr="xxx"
color = 123
[BG 1]
spr="aaa"
color = 456
[BG 2]
spr="bbb"
color = 789
I want to read BG ?? into a slice or map.   Can go-ini support that?

**Comment by Unknwon** [comment]
Hi, I don't think it is possible... since you know it's format, you can iterate sections by yourself and put them into array/map.

**Comment by fastfading** [comment]
只需要列举一个正则表达式 BG.*， 然后把这个加入一个slice 或者map
手写固然可以， 但是如果能加入库，肯定跟方便， 而且ini 配置中有时确实有这种需求
我们在实际应用中确实遇到了

2016-12-21 19:15 GMT+08:00 无闻 <notifications@github.com>:

**Comment by Unknwon** [comment]
>只需要列举一个正则表达式 BG.*然后把这个加入一个slice 或者map

感觉是一个大功能。。:sob:

**Comment by fastfading** [comment]
有没有什么  api 可以把一个sesstion   map 到一个struct 的？

2016-12-22 9:00 GMT+08:00 无闻 <notifications@github.com>:

**Comment by Unknwon** [comment]
https://github.com/go-ini/ini#map-to-struct

**Comment by fastfading** [comment]
section map to struct 没有作用
见图,    secs[i]  里面是有值的  但是map后的结构没有  为何？bug？
<img width="1345" alt="sectionmap" src="https://cloud.githubusercontent.com/assets/8351732/22005695/54d9fddc-dca0-11e6-90c6-1f17cf13eb88.png">

**Comment by Unknwon** [comment]
你没有传递指针类型所有修改当然都是发生在副本上。

```go
val = &type{}
```

或者 

```go
xx.MapTo(&val)
```

**Comment by ccpwcn** [comment]
这样的配置：
host = 192.168.100.64:30000
这样定义字段：
Host       []string `ini:","`
读不出来
写成这样：
Host       []string
也读不出来。
Why???
