### ISSUE TITLE
map to struct 只支持 int  和 float64 类型?

### ISSUE THREAD

**Issue by fastfading** [go-ini/ini#86]
我 定义的struct中的  float32 都没有转成功，并且float32之后的数据也转失败了   是bug 还是设计
但是int32 可以成功的转。  求答复。我64位系统ubuntu

还没试过其他的类型。

如果是设计，请在readme 中写明。

**Comment by fastfading** [comment]
好像是个bug   ， 请修正
问题在这个函数setWithProperType  漏写了reflect.Float32
	case **_reflect.Float32,_** reflect.Float64:
		floatVal, err := key.Float64()
		if err != nil {
			return nil
		}
		field.SetFloat(floatVal)

**Comment by Unknwon** [comment]
Thanks, patch has been pushed!

**Comment by fastfading** [comment]
什么时候能把 slice map的各种类型也加上。([]int32 []int16 []float32....等等)   slice 目前只支持int
uint float64等
我看slice 改起来还比较麻烦

2017-01-17 21:01 GMT+08:00 无闻 <notifications@github.com>:
