### ISSUE TITLE
It is unable to get a full string value if it contains "#" symbol

### ISSUE THREAD

**Issue by grubastik** [go-ini/ini#88]
It is unable to get a full string value if it contains "#" symbol.

Sample of the ini file:
```ini
#===== Start of the file =======
test_value="qwe#123" 
#===== End of the file ======== 
```

Expected result: 
`
{TestValue: qwe#123}
`
Actual result:
`
{TestValue: qwe}
`

**Comment by Unknwon** [comment]
See https://github.com/go-ini/ini#comment...
