### ISSUE TITLE
how will goini handle sections with the same name

### ISSUE THREAD

**Issue by fastfading** [go-ini/ini#89]
type Note struct {
	Typ  string //`ini:"type"`
	Content string
	Cities  []string
	Number [] int
}

[Note]
typ = normal
Content = Hi is a good man!
Cities = HangZhou, Boston
**number**=1,2
**number**=3,4

cfg, err := ini.InsensitiveLoad("./test.ini")
	p := new(Note)
	err = cfg.MapTo(p)
according to my test,  3,4  will replace 1,2
If I want to cat 3,4 to 1,2  what should I do

**Comment by fastfading** [comment]
what is the proper way to handle this situation?
I refer other doc , it seems that , we should cat .  So should we mark this a bug?

**Comment by Unknwon** [comment]
Thanks for the feedback, I think this basically same as https://github.com/go-ini/ini/issues/85.

**Comment by fastfading** [comment]
any plan to support it ?
or just tell me how to modify it ?

**Comment by Unknwon** [comment]
I think it is hard to define a so-called "standard" to handle this, we have to know:

Why we have same keys under a section, and what is the use case for that.

**Comment by fastfading** [comment]
// reflectSliceWithProperType does the opposite thing as setSliceWithProperType.
which function above do the overwrite ?   
I guess we just need replace key.SetValue(buf.String()[:buf.Len()-1]) in reflectSliceWithProperType
with key.AppendValue  ?

**Comment by fastfading** [comment]
the git ini configuration (in issue 85)gives an example for this

**Comment by Unknwon** [comment]
Please use correct Markdown code block notion ``` ` ``` and refers code with links in line number, otherwise it's hard to understand what you're referring to.

**Comment by fastfading** [comment]
func reflectSliceWithProperType(key *Key, field reflect.Value, delim string) error {
    .....
     key.SetValue(buf.String()[:buf.Len()-1])  --> key.AppendValue
}  
sorry I don't how to use markdown

**Comment by Unknwon** [comment]
Duplicated key name are ignored while parsing, change whatever other methods or function would not help, BTW there is no such method `key.AppendValue`...

**Comment by Unknwon** [comment]
I think figure out a way to read/write such keys, but not possible to work with structs.

**Comment by Unknwon** [comment]
>according to my test, 3,4 will replace 1,2
If I want to cat 3,4 to 1,2 what should I do

What do you mean by **cat**?

**Comment by fastfading** [comment]
linux command  cat     ，   the output will be  1,2,3,4

**Comment by Unknwon** [comment]
>the output will be 1,2,3,4

I think it's not going to be implemented.

Instead I might implemented all you to get `[]int{"1,2", "3,4"}`.

**Comment by fastfading** [comment]
number=1,2
number=3,4
var Number [] int = {3,4} //right now logic
var Number [] int = {1,2,3,4} //I expect

if u can offer var Number []string{"1,2", "3,4"}    ,  I can accept it.

**Comment by Unknwon** [comment]
OK, sounds good.

To achieve that, new APIs will be added, what current methods returns remains the same.

New method will be something like `key.ValueWithShadows`.

**Comment by fastfading** [comment]
any plan or schedule on this ?

**Comment by Unknwon** [comment]
OK, please update and see examples here: https://github.com/go-ini/ini/blob/master/key_test.go#L442-L464

**Comment by fastfading** [comment]
could u offer function like InsentiveLoad,  or modify these interfaces
function
for we may need InsentiveShadowLoad or  NoneInsentiveShadowLoad

func Load(source interface{}, others ...interface{}) (*File, error) {
   return LoadSources(LoadOptions{}, source, others...)
}

// LooseLoad has exactly same functionality as Load function
// except it ignores nonexistent files instead of returning error.
func LooseLoad(source interface{}, others ...interface{}) (*File, error) {
   return LoadSources(LoadOptions{Loose: true}, source, others...)
}

// InsensitiveLoad has exactly same functionality as Load function
// except it forces all section and key names to be lowercased.
func InsensitiveLoad(source interface{}, others ...interface{}) (*File, error) {
   return LoadSources(LoadOptions{Insensitive: true}, source, others...)
}


2017-02-22 11:37 GMT+08:00 无闻 <notifications@github.com>:

**Comment by Unknwon** [comment]
Added `ini.ShadowLoad`

**Comment by fastfading** [comment]
ini.ShadowLoad did not work properly
secs[i]= &{ Hi is a good man! [HangZhou Boston] [1 2]
number = "1 2"   //wrong
expect number=[]string{"1,2", "3,4"}     as we discussed before

```
package main

import (
	"log"
	"time"
	 "github.com/go-ini/ini"
)

type Note struct {
	Typ  string //`ini:"type"`
	Content string
	Cities  []string
	Number []string
}

type Person struct {
	Name string
	Age  int `ini:"age"`
	Male bool
	Born time.Time
	Note
	Created time.Time `ini:"-"`
}

func main() {
	cfg, err := ini.LoadSources(ini.LoadOptions{AllowShadows: true},"./test.ini")
	//log.Println(err)

	p := new(Person)
	err = cfg.MapTo(p)
	//log.Println(err)
	log.Println("Person=",p)

	n := new(Note)
	secs := cfg.Sections()
	for i := range secs {
		if secs[i].Name()=="Note" || secs[i].Name()=="note" {
			err = secs[i].MapTo(n)
			log.Println("secs[i]=",n)
		}
	}
	//err = cfg.Section("Note").MapTo(n)
	//log.Println("Note=",n)
	log.Println(err)
}
```


```
Name = Unknwon
age = 21
Male = true
Born = 1993-01-01T20:17:05Z

[Note]
typ = normal
Content = Hi is a good man!
Cities = HangZhou, Boston
Number=1,2
Number=3,4
```

**Comment by Unknwon** [comment]
You need to use `key.ValueWithShadows`.

**Comment by fastfading** [comment]
So(strings.Join(cfg.Section(`remote "origin"`).Key("url").ValueWithShadows(), " "), ShouldEqual,
				"https://github.com/Antergone/test1.git https://github.com/Antergone/test2.git")

how this works ?    I am not sure ? 
Can it map to structure automatically ? 
could u show me in my example?
I just want to it map to structure. 
but your example did not show how ,  
what will cfg.Section(`remote "origin"`).Key("url").ValueWithShadows() return ?

**Comment by Unknwon** [comment]
https://gowalker.org/github.com/go-ini/ini#Key_ValueWithShadows

>Can it map to structure automatically ?

Currently, no.

**Comment by fastfading** [comment]
it is a great advantage for go-ini that it can map ini directly to
structure just like go-json, compare to other ini lib
did  u  have any plan to do this?   so it can work perfectly

2017-03-09 9:00 GMT+08:00 无闻 <notifications@github.com>:

**Comment by Unknwon** [comment]
Yes, it is possible to implement, with few notes:

We need a new tag syntax (probably `ini:",,shadow"`) to indicate that a field of struct should be mapped with shadow values. That way, we are able to be consistent when you reflect back from struct to a INI file.

Suggest open a new issue to address this ability.
