### ISSUE TITLE
Does not work with quoted values

### ISSUE THREAD

**Issue by ccampbell** [go-ini/ini#9]
INI format is somewhat open, but most implementations support quoted values both double quotes and single quotes.

See http://en.wikipedia.org/wiki/INI_file#Quoted_values

For example

```ini
some_key = "some value"
some_other_key = 'some other value'
```

Unless I am missing something, this library keeps the quotes as part of the value instead of ignoring them

**Comment by Unknwon** [comment]
Hi @ccampbell , this library uses back quote `xxx` and triple quotes `"""xxx"""` for keys and values:

```ini
foo = `some value`
bar = """line1
line2
line3"""
```
and uses normal quotes `"xxx"` for only keys:

```ini
"key with = special chars" = my value
```

Not sure if answers your question.

But if you insist to have `"` work with values, I can make it. :smile:

**Comment by ccampbell** [comment]
@Unknwon thanks for the reply.  The issue is that I am trying to reuse a config file from another project for an rpc service and pulling from a python cfg file.  It is not ini but it is basically the same.  In python the quotes are required or else it will break.  

I have been working around it by stripping the quotes out after pulling the value, but I do think it is worth handling in your package :smile:

**Comment by Unknwon** [comment]
Hi @ccampbell , I've pushed code and please use `go get -u gopkg.in/ini.v1` to update and test, thanks!

**Comment by ccampbell** [comment]
Thanks, seems to work :smile:

**Comment by Unknwon** [comment]
@ccampbell thanks your confirmation!
