### ISSUE TITLE
saves incorrectly when value contains ';'

### ISSUE THREAD

**Issue by ziflex** [go-ini/ini#90]
Hi there,

I have noticed that when value contains ';' symbol, lib saves file in incorrect format.
Here is an example

```ini
[Desktop Entry]
Name          = Atom
Comment       = A hackable text editor for the 21st Century.
GenericName   = Text Editor
Exec          = /usr/share/atom/atom %F
Icon          = atom
Type          = Application
StartupNotify = true
;GTK;Utility;TextEditor;Development;
Categories    = GNOME
MimeType      = text/plain
```

``Categories`` key should contain value ``GNOME;GTK;Utility;TextEditor;Development;``

I see there is a note about this behavior in README.

Is there a workaround for it?

**Comment by Unknwon** [comment]
Are you reading from file then save or you just programed to generate this file?

**Comment by ziflex** [comment]
@Unknwon reading and then saving. That's the problem. 
Currently I have to make a dirty check whether a key has a comment and add comment to the end of the key value

```go
			if key.Comment != "" && strings.Contains(key.Comment, ";") {
				key.SetValue(fmt.Sprintf("%s%s", val, key.Comment))
				key.Comment = ""
			}
```

**Comment by Unknwon** [comment]
Simply trick... https://github.com/go-ini/ini#comment

**Comment by ziflex** [comment]
I understand that there was a reason of adding this, so I'm just wondering what if it had been possible to configure this behavior via settings.

**Comment by ziflex** [comment]
this trick doesn't work. since lib treat these values as comments when you load file.

**Comment by Unknwon** [comment]
>If you want to save a value with # or ;, please quote them with ` or """.

**Comment by slaftos** [comment]
ini file processing in windows, the embedded ; and # are valid values.  Take for example an sql connect string or statement in an ini file.
Not being able to allow this makes this a non portable package.
