### ISSUE TITLE
Map shadow key to structure

### ISSUE THREAD

**Issue by fastfading** [go-ini/ini#92]
since go-ini already support {AllowShadows: true}
I wish to could map to structure directly
example {AllowShadows: true}
[Note]
typ = normal
Number=1,2
Number=3,4

Number = []string{"1,2","3,4"}  or  Number = []string{"1","2","3","4"} 
I could accept these 2 above

**Comment by Unknwon** [comment]
OK, shadows currently only work with `[]string`.

```go
type MyStruct struct {
    ...
    Numbers [] string `ini:",,allowshadow"`
    ...
}
```

```ini
Numbers = 1,2
Numbers = 3,4
```

Result:

```
MyStruct.Numbers: []string{"1", "2", "3", "4"}
```

**Comment by fastfading** [comment]
and if I define like blew

type MyStruct struct {
    ...
    Numbers [] int `ini:",,allowshadow"`
    ...
}

result would be     MyStruct.Numbers: []int{1, 2, 3, 4}

right?



2017-03-11 10:51 GMT+08:00 无闻 <notifications@github.com>:

**Comment by Unknwon** [comment]
No,

![image](https://cloud.githubusercontent.com/assets/2946214/23839343/c712ff86-0773-11e7-9d60-f2f97fcc7bba.png)

**Comment by fastfading** [comment]
will this be improved later
is this need a new issue to track ?
or  it will be done and closed with this issue

2017-03-13 10:32 GMT+08:00 无闻 <notifications@github.com>:

**Comment by Unknwon** [comment]
I'm just lazy... won't do it until you asked. :trollface:

**Comment by Unknwon** [comment]
`[]int` and `[]int64` should work now!

**Comment by fastfading** [comment]
how about float64
I think this 3   int  int64 float64 should work ,  at least

2017-03-13 12:11 GMT+08:00 无闻 <notifications@github.com>:

**Comment by Unknwon** [comment]
OK... working on it.

**Comment by Unknwon** [comment]
OK, added all...

**Comment by fastfading** [comment]
thank you very much ,   you are coding leifeng
just one more question ,  what should I use this `ini:",,allowshadow"`
there are many usage as I see. how can I combine them
for example Number []int `int:"number, , allowshadow"` ????? what is the
parameter mean in para1 *,* para2 *,* para3

Age  int `ini:"age"`

Created time.Time `ini:"-"`

Number []string `ini:",,allowshadow"`

type MyStruct struct {
    ...
    Numbers [] string `ini:",,allowshadow"`
    ...
}

Numbers = 1,2Numbers = 3,4

Result:

MyStruct.Numbers: []string{"1", "2", "3", "4"}



2017-03-14 9:38 GMT+08:00 无闻 <notifications@github.com>:

**Comment by Unknwon** [comment]
`ini:"numbers,omitempty,allowshadow"`
