### ISSUE TITLE
Allow embedded ; and # in values

### ISSUE THREAD

**Issue by slaftos** [go-ini/ini#93]
ini file processing in windows, the embedded ; and # are valid values. Take for example an sql connect string or statement in an ini file.

Not being able to allow this makes this package difficult to use in windows environments

It appears that all that would be required is to condition this block of code

		i := strings.IndexAny(line, "#;")
		if i > -1 {
			p.comment.WriteString(line[i:])
			line = strings.TrimSpace(line[:i])
		}

beginning at line 228 in parser.go

**Comment by Unknwon** [comment]
Will add an option for this.

**Comment by slaftos** [comment]
Works as advertised!
thank you
