### ISSUE TITLE
Able to get child sections

### ISSUE THREAD

**Issue by bruceauyeung** [go-ini/ini#95]
for example:
~~~
[node]
...
[node.biz1]
...
[node.biz2]
...
[node.biz3]
...
[node.bizN]
...
~~~
in this situation, we are not sure that how many child sections will appear, child section names dont even have a pattern.
so if we can do getSectionWildcard("node.*") or something like that, it will be very handy for this situation.

thanks for your great work!

**Comment by Unknwon** [comment]
How do you handle data returned from `getSectionWildcard`? In what type?

**Comment by bruceauyeung** [comment]
@Unknwon section slice sounds good to me.

**Comment by Unknwon** [comment]
Just to make things clear... I think this method should be called `getChildSections`... in your case, it would be `getChildSections("node")`.

**Comment by bruceauyeung** [comment]
another api i suggest: `getChildSections(sectionName string)`
what do you think ?

**Comment by Unknwon** [comment]
What are you talking?

**Comment by bruceauyeung** [comment]
both api are valueable for different situations. getChildSections is better in my situation of course.

**Comment by Unknwon** [comment]
![image](https://cloud.githubusercontent.com/assets/2946214/24403092/60761930-1389-11e7-9269-5cf81aa41126.png)

???

**Comment by Unknwon** [comment]
Added, usage:

```go
children := cfg.ChildSections(name)
```

or 

```go
children := sec.ChildSections()
```

**Comment by bruceauyeung** [comment]
@Unknwon thanks for your quick and nice work! its a really great feature i think.

**Comment by bruceauyeung** [comment]
@Unknwon when i replyed, i didn't notice your suggest `getChildSections("node")`( i was typing and didn't reload the page), so i proposaled my api just as same as yours. sorry for this. anyway, this is what i want and i think it definitely can help other people.

**Comment by Unknwon** [comment]
Ah, good, closed as implemented.
