### ISSUE TITLE
should throw error when invalid input

### ISSUE THREAD

**Issue by bruceauyeung** [go-ini/ini#96]
saying i have
~~~
[user1]
name=bruce
age=a30
~~~

my struct
~~~
type user struct {
    Name string
    Age int
}
~~~
when i try to 
~~~
err = cfg.MapTo(u)
~~~
i expect an error is throwed out because `a30` is not a valid int value,  but actually go-ini didn't throw any error

**Comment by Unknwon** [comment]
Hi,

1. This is expected behavior, currently only error that makes library impossible to continue will return an error. Other errors like type parse failure would be ignored and use zero value.
2. I can add another method like `StrictMapTo` to throw error every possible error.

**Comment by bruceauyeung** [comment]
@Unknwon thanks for your great work! I am expecting `StrictMapTo`

**Comment by Unknwon** [comment]
Hi, `StrictMapTo` functions/methods have been added, please update and test!

**Comment by bruceauyeung** [comment]
@Unknwon tested, everything works as expected, thanks!
