### ISSUE TITLE
Address="" behaves inconsistently

### ISSUE THREAD

**Issue by bruceauyeung** [go-ini/ini#97]
i have .ini file
~~~
Name="bruce"
Address=""
~~~
after parsed into a struct Person, p.Address will hold a string value `""""`(not empty string but two double quotes in it)
i expect p.Address will equal to empty string

@Unknwon

**Comment by Unknwon** [comment]
Thanks for the report, should work now! Please update the package.

**Comment by bruceauyeung** [comment]
@Unknwon its fixed now, thanks for your work!
