### ISSUE TITLE
Remove redundant quotes with IgnoreInlineComment=true

### ISSUE THREAD

**Issue by ziflex** [go-ini/ini#99]
Hi there,

Finally, the lib can ignore inline comments. It's great and works like a charm. But can we now remove redundant quotes for values that contain ``;`` or ``#`` symbols when ``IgnoreInlineComment`` is set to true?

Specifically, here
https://github.com/go-ini/ini/blob/1730955e3146956d6a087861380f9b4667ed5071/ini.go#L502

**Comment by Unknwon** [comment]
Thanks for the report! Please update and try again!

**Comment by ziflex** [comment]
Fixed, great! Thank you!
